### PR TITLE
fix: ensure assistant messages with tool_calls include content field

### LINKED ISSUE #6717: Assistant messages missing 'content' field when sending tool calls to certain OpenAI-compatible providers
# GitHub Issue: Assistant messages missing 'content' field when sending tool calls

**Title:** Assistant messages missing 'content' field when sending tool calls to certain OpenAI-compatible providers

---

**Describe the bug**

💡 Before filing, please check common issues:
https://block.github.io/goose/docs/troubleshooting

📦 To help us debug faster, attach your **diagnostics zip** if possible.
👉 How to capture it: https://block.github.io/goose/docs/troubleshooting/diagnostics-and-reporting/

When Goose sends an `assistant` message containing tool calls (via the OpenAI provider engine), it omits the `content` field entirely if there is no accompanying text content. While this is valid in some OpenAI contexts, many strict OpenAI-compatible providers (such as the TAMU AI API or certain custom proxies) require the `content` field to be present (e.g., as an empty string `""` or `null`) whenever `tool_calls` are provided. This results in a `400 Bad Request` from the provider.

The issue is located in [crates/goose/src/providers/formats/openai.rs](file:///Users/kcao/goose-source/goose_src/crates/goose/src/providers/formats/openai.rs#L63-L259). The `format_messages` function only adds the `content` key if `content_array` or `text_array` is non-empty.

---

**To Reproduce**
1. Configure a custom OpenAI provider in `~/.config/goose/config.yaml` using a base URL that points to a strict OpenAI-compatible API (e.g., TAMU API).
2. Start a goose session: `goose session`.
3. Ask a question that requires a tool call, such as "What time is it?".
4. See error: The provider returns a `400 Bad Request` because the assistant message lacks a `content` field.

---

**Expected behavior**
Goose should include `"content": ""` or `"content": null` in the assistant message when tool calls are present but text content is not.

---

**Screenshots**
N/A

---

**Please provide the following information**
- **OS & Arch:** macOS arm64
- **Interface:** CLI
- **Version:** v1.21.1
- **Extensions enabled:** Developer (default)
- **Provider & Model:** custom_tamu_ai (OpenAI engine) / protected.gpt-5.2

---

**Additional context**
Workaround involves using a proxy script to inject the missing field:
```python
if msg.get("role") == "assistant" and "content" not in msg:
    msg["content"] = ""
```
This confirms that adding the field resolves the issue.

### PR DESCRIPTION
**Pull request by fl-sean03**
## Summary

Fixes #6717 — assistant messages missing `content` field when sending tool calls to certain OpenAI-compatible providers.

Some strict OpenAI-compatible providers (e.g., `deepseek-chat`, certain local inference servers) require the `content` field to be present on assistant messages even when only tool calls are being sent. When goose formats messages without text content alongside tool calls, the `content` field is omitted entirely, causing these providers to reject the request.

## Changes

- **`crates/goose/src/providers/formats/openai.rs`**: After constructing the converted message, check if an assistant message has `tool_calls` present but `content` is missing, and set `content` to `null` in that case.
- Added two focused tests:
  - `test_format_messages_tool_calls_only_sets_content_null` — verifies `content: null` is set when assistant has only tool_calls
  - `test_format_messages_tool_calls_with_text_keeps_content_string` — ensures text content is preserved when both text and tool calls exist

## Test Plan

- [x] New unit tests pass
- [x] Existing test suite unaffected
- [ ] Manual test with a strict OpenAI-compatible provider (e.g., `deepseek-chat`)

### CODE REVIEW

File: crates/goose/src/providers/formats/openai.rs [hunk 1]
```diff
@@ -1643,6 +1653,63 @@ data: [DONE]
         Ok(())
     }
 
+    #[test]
```
Comment (katzdave) [inline crates/goose/src/providers/formats/openai.rs]: Tests are all very long winded, can we delete?

File: crates/goose/src/providers/formats/openai.rs [hunk 2]
```diff
@@ -247,6 +247,16 @@ pub fn format_messages(messages: &[Message], image_format: &ImageFormat) -> Vec<
             converted["content"] = json!(text_array.join("\n"));
         }
 
+        // Ensure assistant messages with tool_calls always have a content field.
+        // Some strict OpenAI-compatible providers require "content" to be present
```
Comment (katzdave) [inline crates/goose/src/providers/formats/openai.rs:250]: Let's just leave this line of this comment describing the reason for the code.

File: crates/goose/src/providers/formats/openai.rs [hunk 3]
```diff
@@ -247,6 +247,15 @@ pub fn format_messages(messages: &[Message], image_format: &ImageFormat) -> Vec<
...
         }
 
+        // Some strict OpenAI-compatible providers require "content" to be present
+        // (even as null) when tool_calls are provided. See #6717.
+        if message.role == Role::Assistant
+            && converted.get("tool_calls").is_some()
+            && converted.get("content").is_none()
+        {
+            converted["content"] = json!(null);
+        }
```
[the remark this answers is not in the document]
Comment (fl-sean03) [reply crates/goose/src/providers/formats/openai.rs:257]: Fixed — PR description updated to match the actual test names. The original tests were deleted per @katzdave's request, and two new focused tests have been added: `test_format_messages_tool_calls_only_sets_content_null` and `test_format_messages_tool_calls_with_text_keeps_content_string`.

[the remark this answers is not in the document]
Comment (fl-sean03) [reply crates/goose/src/providers/formats/openai.rs:257]: Added two tests in the latest commit (cef2a90): `test_format_messages_tool_calls_only_sets_content_null` asserts `content` is present and `null` for assistant tool-call-only messages. `test_format_messages_tool_calls_with_text_keeps_content_string` asserts mixed text+tool calls keeps `content` as a string.

File: crates/goose/src/providers/formats/openai.rs [hunk 4]
```diff
@@ -968,6 +977,66 @@ mod tests {
         Ok(())
     }
 
+    #[test]
+    fn test_format_messages_tool_calls_only_sets_content_null() -> anyhow::Result<()> {
```
Comment (katzdave) [inline crates/goose/src/providers/formats/openai.rs]: I don't think we need tests at all for this fix, would prefer we delete completely. Since it's just directly mirroring what's being set above and asserting that.

**Comment by fl-sean03** [comment]
Tests removed — agreed they were just mirroring the fix directly. Thanks for the review!

File: crates/goose/src/providers/formats/openai.rs (hunk 4 above)
Comment (fl-sean03) [reply crates/goose/src/providers/formats/openai.rs]: Makes sense — removing the tests now.

Comment (fl-sean03) [reply crates/goose/src/providers/formats/openai.rs]: Makes sense — removing the tests now.
