### PR TITLE
Fix voice dictation provider selection bug

### LINKED ISSUE #3226: Cannot select OpenAI Whisper Voice Dictation after switching to ElevenLabs
**Describe the bug**
Selected elevenlabs in dropdown to see how it works.  After that, OpenAI Whisper is greyed out with the phrase (not configured) in the dropdown, and it cannot be selected.

Note: Please check the common issues on https://block.github.io/goose/docs/troubleshooting before filing a report

**To Reproduce**
1. On Advanced Settings, scroll down to Voice Dictation; dropdown box may say OpenAI Whisper.
2. Click on dropdown box, select ElevenLabs.  Box changes to ask for API key.
3. Click back on dropdown to see OpenAI Whisper is not selectable.

**Expected behavior**
Expected to see OpenAI option available. Should also show note ("No key needed for Block Internal")

**Screenshots**

Image

**Please provide following information:**
 - **OS & Arch:** MacOS Seq 15.5 M2 Max
 - **Interface:** GUI
 - **Version:** Version 1.0.31-block.202507011518-0c36f (1.0.31-block.202507011518-0c36f)
 - **Extensions enabled:** default and DataMCP
 - **Provider & Model:** Default Claude-4-Sonnet

**Additional context**

### PR DESCRIPTION
**Pull request by JJSwigut**
# Fix voice dictation provider selection bug

## What
- Removed the `disabled` attribute from OpenAI Whisper option in the voice dictation provider dropdown
- Added dropdown refresh logic to update OpenAI configuration status when dropdown is opened
- Users can now switch back to OpenAI Whisper after selecting ElevenLabs
- Maintained visual indicator showing "(not configured)" when OpenAI is not set up

## Why
This fixes a critical UX bug where users would get permanently stuck after exploring ElevenLabs. The issue occurred because:
1. User starts with OpenAI Whisper (working or not)
2. User clicks ElevenLabs to explore it
3. **BUG**: OpenAI Whisper becomes disabled and unclickable
4. User cannot return to OpenAI, even to configure it

The root cause was the `disabled={!hasOpenAIKey}` attribute that prevented any interaction with the OpenAI option once it was deemed "not configured".

## Key File Changes
- `ui/desktop/src/components/settings/dictation/DictationSection.tsx`: 
  - Removed `disabled` attribute from OpenAI Whisper button
  - Added `handleDropdownToggle` function to refresh provider status
  - Updated dropdown button to use new handler
  - Maintained configuration status display logic

## Impact
- **Block Internal users**: Can now select OpenAI Whisper without API key configuration
- **External users**: Can select OpenAI Whisper to configure it or use existing setup
- **All users**: No longer get stuck in ElevenLabs after exploring it

Fixes #3226 and #3280

https://github.com/user-attachments/assets/7106a325-daed-4931-85e5-8d79bf231be6

### CODE REVIEW

File: ui/desktop/src/components/settings/dictation/DictationSection.tsx [hunk 1]
```diff
@@ -97,6 +97,25 @@ export default function DictationSection() {
     checkOpenAIKey();
   }, [getProviders]);
 
+  // Also check OpenAI configuration when dropdown is opened
```
Comment (DOsinga) [inline ui/desktop/src/components/settings/dictation/DictationSection.tsx]: remove the comment

File: ui/desktop/src/components/settings/dictation/DictationSection.tsx [hunk 2]
```diff
@@ -97,6 +97,25 @@ export default function DictationSection() {
...
+  const handleDropdownToggle = async () => {
+    const newShowState = !showProviderDropdown;
+    setShowProviderDropdown(newShowState);
+    
+    // Refresh OpenAI configuration status when opening dropdown
```
Comment (DOsinga) [inline ui/desktop/src/components/settings/dictation/DictationSection.tsx]: remove this one also

File: ui/desktop/src/components/settings/dictation/DictationSection.tsx [hunk 3]
```diff
@@ -97,6 +97,25 @@ export default function DictationSection() {
...
+    if (newShowState) {
+      try {
+        const providers = await getProviders(true); // Force refresh
+        const openAIProvider = providers.find((p) => p.name === 'openai');
+        const isConfigured = openAIProvider?.is_configured || false;
```
Comment (DOsinga) [inline ui/desktop/src/components/settings/dictation/DictationSection.tsx]: `!!openAIProvider?.is_configured`

File: ui/desktop/src/components/settings/dictation/DictationSection.tsx [hunk 4]
```diff
@@ -97,6 +97,25 @@ export default function DictationSection() {
...
 
+  // Also check OpenAI configuration when dropdown is opened
+  const handleDropdownToggle = async () => {
+    const newShowState = !showProviderDropdown;
+    setShowProviderDropdown(newShowState);
+    
+    // Refresh OpenAI configuration status when opening dropdown
+    if (newShowState) {
+      try {
+        const providers = await getProviders(true); // Force refresh
```
Comment (DOsinga) [inline ui/desktop/src/components/settings/dictation/DictationSection.tsx]: remove comment

**Review by DOsinga — APPROVED** [review]
thanks for doing this! marked some LLM things to remove, otherwise good to go
