### PR TITLE
Fix context progress bar not resetting after /clear command

### LINKED ISSUE #5651: Context progress bar not resetting after /clear command
**Describe the bug**

💡 Before filing, please check common issues:  
https://block.github.io/goose/docs/troubleshooting  

📦 To help us debug faster, attach your **diagnostics zip** if possible.  
👉 How to capture it: https://block.github.io/goose/docs/troubleshooting/diagnostics-and-reporting/

---

**To Reproduce**
1. Start a Goose CLI session
  2. Send several messages to build up context usage (e.g., ask multiple questions)
  3. Observe the context progress bar showing token usage (e.g., Context: ●●●●●●●○○○ 70% (189053/272000 tokens))
  4. Type /clear to clear the chat context
  5. Observe that the context progress bar still shows the old percentage instead of resetting to 0%

---

**Expected behavior**
  After running /clear, the context progress bar should reset to show 0% usage with all empty circles:
  Context: ○○○○○○○○○○ 0% (0/272000 tokens)

---

**Screenshots**
Image

---

**Please provide the following information**
- **OS & Arch:** macOS 26
- **Interface:** CLI
- **Version:** 1.13.0
- **Extensions enabled:** chromedevtools, developer, computercontroller, todo
- **Provider & Model:** OpenAI – gpt-5

---

**Additional context**

### PR DESCRIPTION
**Pull request by catbilyeu**
Fixes #5651

## Summary
When using /clear to reset the conversation, the context progress bar was showing the old token usage percentage instead of resetting to 0%.

This was because the /clear command cleared the messages but did not reset the token count metadata stored in the session database.

Changes:
- Reset total_tokens, input_tokens, and output_tokens to 0 when clearing the conversation in the /clear command handler
- Token counts are now properly synchronized with the cleared state

### Type of Change

- [ ] Feature
- [X] Bug fix
- [ ] Refactor / Code quality
- [ ] Performance improvement
- [ ] Documentation
- [ ] Tests
- [ ] Security fix
- [ ] Build / Release
- [ ] Other (specify below)

### AI Assistance

- [X] This PR was created or reviewed with AI assistance

### Testing
- Manually tested by building and running goose-cli v1.13.0
- Verified context bar resets to 0% after /clear command
- Confirmed no compilation errors with cargo check

### Related Issues
Relates to #5651  
Discussion: https://github.com/block/goose/issues/5651

### Screenshots/Demos (for UX changes)
Before: 
contextbarbug
After:   
PNG image

### Submitting a Recipe?

**Email**:

### CODE REVIEW

File: crates/goose-cli/src/session/mod.rs [hunk 1]
```diff
@@ -618,6 +618,10 @@ impl CliSession {
                 input::InputResult::Clear => {
                     save_history(&mut editor);
 
+                    // Perform all database operations first, only clear in-memory state if both succeed
```
Comment (katzdave) [inline crates/goose-cli/src/session/mod.rs]: don't need any of these comments. Nor below.

File: crates/goose-cli/src/session/mod.rs [hunk 2]
```diff
@@ -628,7 +632,29 @@ impl CliSession {
                         continue;
                     }
 
+                    // Step 2: Reset token counts in session metadata
+                    if let Err(e) = SessionManager::update_session(&self.session_id)
+                        .total_tokens(Some(0))
+                        .input_tokens(Some(0))
+                        .output_tokens(Some(0))
+                        .accumulated_total_tokens(Some(0))
```
Comment (katzdave) [inline crates/goose-cli/src/session/mod.rs]: can we avoid updating the accumulated tokens as your past usage should impact the session cost. CLI doesn't render these, but if you opened this session in desktop would be good to have.

File: crates/goose-cli/src/session/mod.rs [hunk 3]
```diff
@@ -628,7 +632,29 @@ impl CliSession {
...
+                        }
+                        continue;
+                    }
+
+                    // Step 3: Only after both DB operations succeed, clear in-memory state
                     self.messages.clear();
+
                     tracing::info!("Chat context cleared by user.");
                     output::render_message(
                         &Message::assistant().with_text("Chat context cleared."),
```
Comment (katzdave) [inline crates/goose-cli/src/session/mod.rs]: Can we add a \n here, saw this also didn't look that pretty.

File: crates/goose-cli/src/session/mod.rs [hunk 4]
```diff
@@ -628,7 +632,29 @@ impl CliSession {
...
+                        .accumulated_total_tokens(Some(0))
+                        .accumulated_input_tokens(Some(0))
+                        .accumulated_output_tokens(Some(0))
+                        .apply()
+                        .await
+                    {
+                        output::render_error(&format!("Failed to reset token counts: {}", e));
+                        // Token reset failed, but conversation was already cleared in DB
+                        // Restore consistency by syncing in-memory state with DB (empty conversation)
+                        if let Ok(session) = SessionManager::get_session(&self.session_id, true).await {
```
Comment (katzdave) [inline crates/goose-cli/src/session/mod.rs]: I don't think we need this part. Let's just throw an error and continue. Shouldn't really happen in practice, and if we're having problems writing to the session this is unlikely to work either.

File: crates/goose-cli/src/session/mod.rs [hunk 5]
```diff
@@ -628,10 +628,22 @@ impl CliSession {
...
+                        output::render_error(&format!("Failed to reset token counts: {}", e));
+                        continue;
+                    }
+
                     self.messages.clear();
+
                     tracing::info!("Chat context cleared by user.");
                     output::render_message(
-                        &Message::assistant().with_text("Chat context cleared."),
+                        &Message::assistant().with_text("\nChat context cleared."),
```
Comment (katzdave) [inline crates/goose-cli/src/session/mod.rs]: I think \n on the other end I wasn't seeing a line break before the next prompt but if this renders well can go with this too.

**Review by katzdave — APPROVED** [review]
Thanks for the fix!
