### PR TITLE
fix: validate function call json schemas for openai

### LINKED ISSUE #933: Jetbrains extension fails with gpt-4o
I enabled the jetbrains tool but can't quite figure out how to use it. Could you help with some instructions? I tried asking to search with jetbrains/intellij and also asked for what functionality does the extension/tool offer. Neither gave me a good result. Do I need to setup something on the IDE side?

### PR DESCRIPTION
**Pull request by wendytang**
Users reporting openai incompatibility with certain extensions.

Fixes #933, related to #945

Extensions are not providing valid json schemas for openai function tool calling. Adds a function to validate the schema and add missing json schema fields
```
    "function": {
        "name": "get_weather",
        "description": "Get current temperature for a given location.",
        "parameters": {
            "type": "object",
            "properties": {
                "location": {
                    "type": "string",
                    "description": "City and country e.g. Bogotá, Colombia"
                }
            },
            "required": [
                "location"
            ],
            "additionalProperties": False
        },
        "strict": True
    }
```

Databricks likely handled the missing fields on their end.

Tests:
- [x] jetbrains tool call successful with openai, gpt4o, o1, o3-mini
- [x] jetbrains tool call successful with databricks, goose

### CODE REVIEW

**Comment by angiejones** [comment]
bless you 🙌🏾

File: crates/goose/src/providers/formats/openai.rs [hunk 1]
```diff
@@ -253,6 +253,36 @@ pub fn get_usage(data: &Value) -> Result<Usage, ProviderError> {
     Ok(Usage::new(input_tokens, output_tokens, total_tokens))
 }
 
+/// Validates and fixes tool schemas to ensure they have proper parameter structure.
+/// If parameters exists, ensures it has properties and required fields, or removes parameters entirely.
+pub fn validate_tool_schemas(tools: &mut [Value]) {
+    for tool in tools.iter_mut() {
+        if let Some(function) = tool.get_mut("function") {
+            if let Some(parameters) = function.get_mut("parameters") {
```
Comment (salman1993) [inline crates/goose/src/providers/formats/openai.rs:261]: i think the tool.function.parameters uses JSON Schema.
https://platform.openai.com/docs/api-reference/chat/create#chat-create-tools

would it make sense to use a validator crate like this one? 
https://docs.rs/jsonschema/latest/jsonschema/

Comment (wendytang) [reply crates/goose/src/providers/formats/openai.rs:261]: This would correct the JSON Schemas that weren't properly provided! 

> would it make sense to use a validator crate like this one?
> https://docs.rs/jsonschema/latest/jsonschema/

Yes, but not here

File: crates/goose/src/providers/formats/openai.rs [hunk 2]
```diff
@@ -253,6 +253,62 @@ pub fn get_usage(data: &Value) -> Result<Usage, ProviderError> {
...
+            }
+
+            // Recursively validate properties if it exists
+            if let Some(properties) = params_obj.get_mut("properties") {
+                if let Some(properties_obj) = properties.as_object_mut() {
+                    for (_key, prop) in properties_obj.iter_mut() {
+                        if prop.is_object()
+                            && (prop.get("type").and_then(|t| t.as_str()) == Some("object"))
+                        {
+                            ensure_valid_json_schema(prop);
```
Comment (wendytang) [inline crates/goose/src/providers/formats/openai.rs:296]: we could put a recursive counter here, but I don't think extensions are going to have massively nested json schemas

File: crates/goose/src/providers/formats/openai.rs [hunk 3]
```diff
@@ -253,6 +253,62 @@ pub fn get_usage(data: &Value) -> Result<Usage, ProviderError> {
...
+            .get("type")
+            .and_then(|t| t.as_str())
+            .map_or(true, |t| t == "object"); // Default to true if no type is specified
+
+        // Only apply full schema validation to object types
+        if is_object_type {
+            // Ensure properties field exists and is an object
+            if !params_obj.contains_key("properties") {
+                params_obj.insert("properties".to_string(), json!({}));
+            }
```
Comment (kalvinnchau) [inline crates/goose/src/providers/formats/openai.rs]: nit: think you can simplify the logic here and the other 2 checks below with:
```suggestion
            params_obj.entry("properties").or_insert_with(|| json!({}));
```

https://docs.rs/serde_json/latest/serde_json/map/enum.Entry.html#method.or_insert_with

Comment (wendytang) [reply crates/goose/src/providers/formats/openai.rs]: good call

File: crates/goose/src/providers/formats/openai.rs [hunk 4]
```diff
@@ -253,6 +253,52 @@ pub fn get_usage(data: &Value) -> Result<Usage, ProviderError> {
...
+            params_obj.entry("properties").or_insert_with(|| json!({}));
+            params_obj.entry("required").or_insert_with(|| json!([]));
+            params_obj.entry("type").or_insert_with(|| json!("object"));
+
+            // Recursively validate properties if it exists
+            if let Some(properties) = params_obj.get_mut("properties") {
+                if let Some(properties_obj) = properties.as_object_mut() {
+                    for (_key, prop) in properties_obj.iter_mut() {
+                        if prop.is_object()
+                            && (prop.get("type").and_then(|t| t.as_str()) == Some("object"))
```
Comment (yingjiehe-xyz) [inline crates/goose/src/providers/formats/openai.rs]: do we need to set default to true like line 277?

File: crates/goose/src/providers/formats/openai.rs [hunk 5]
```diff
@@ -326,6 +375,70 @@ mod tests {
...
+                    "type": "object"
+                }
+            }
+        })];
+
+        validate_tool_schemas(&mut tools);
+
+        let params = tools[0]["function"]["parameters"].as_object().unwrap();
+        assert!(params.contains_key("properties"));
+        assert!(params.contains_key("required"));
```
Comment (yingjiehe-xyz) [inline crates/goose/src/providers/formats/openai.rs]: instead of checking each field, can we compare the whole json? Like 

```
expected = vec![json!({
            "type": "function",
            "function": {
                "name": "test_func",
                "description": "test description",
                "parameters": {
                    "type": "object",
                    "properties": {},
                    "required": []
                }
            }
        })];
assert_eq!(actual, expected);
```

**Comment by wendytang** [comment]
how many people do I have to ask for approval to get a fix in...

**Comment by wendytang** [comment]
I give up

**Review by angiejones — APPROVED** [review]

**Review by michaelneale — APPROVED** [review]
oh very nice!

I wonder if we need similar thing for gemini too!

File: crates/goose/src/providers/formats/openai.rs (hunk 2 above)
Comment (michaelneale) [reply crates/goose/src/providers/formats/openai.rs:296]: yeah I would hope they wouldn't!
