### PR TITLE
Fix GCP Vertex AI global endpoint support for Gemini 3 models

### LINKED ISSUE #6186: GCP Vertex AI provider doesn't support global endpoint for Gemini 3 models
**Describe the bug**

Gemini 3 models (`gemini-3-pro-preview`, `gemini-3-flash-preview`) require the global endpoint on Vertex AI. Setting `GCP_LOCATION=global` does not work because the provider constructs an invalid URL.

In `crates/goose/src/providers/gcpvertexai.rs`:
```rust
let host = format!("https://{}-aiplatform.googleapis.com", location);
```

This produces `https://global-aiplatform.googleapis.com` instead of `https://aiplatform.googleapis.com`.

---

**To Reproduce**
1. Set config:
   ```yaml
   GOOSE_PROVIDER: gcp_vertex_ai
   GOOSE_MODEL: gemini-3-pro-preview
   GCP_LOCATION: global
   ```
2. Run `goose session`
3. Send any message
4. Request fails

---

**Expected behavior**

When `GCP_LOCATION=global`, use endpoint `https://aiplatform.googleapis.com` with `locations/global` in the path.

---

**Please provide the following information**
- **OS & Arch:** macOS 26.1 arm64
- **Interface:** CLI
- **Version:** 1.17.0
- **Extensions enabled:** Developer Tools
- **Provider & Model:** GCP Vertex AI – gemini-3-pro-preview

---

**Additional context**

Regional endpoint returns 404:
```bash
curl -X POST "https://us-central1-aiplatform.googleapis.com/.../gemini-3-pro-preview:generateContent"
# 404 NOT_FOUND
```

Global endpoint works:
```bash
curl -X POST "https://aiplatform.googleapis.com/v1/projects/{project}/locations/global/publishers/google/models/gemini-3-pro-preview:generateContent"
# Success
```

### PR DESCRIPTION
**Pull request by clouatre**
## Summary
Fixes the GCP Vertex AI provider to support the global endpoint required for Gemini 3 models. The previous implementation incorrectly constructed the URL as `https://global-aiplatform.googleapis.com` instead of `https://aiplatform.googleapis.com`.

### Type of Change
- [x] Bug fix

### AI Assistance
- [x] This PR was created or reviewed with AI assistance

### Testing
**Unit Tests:**
- All 11 tests passing (4 new tests added, 7 existing tests still passing)
- New tests: `test_gcp_location_display`, `test_gcp_location_is_global`, `test_build_host_url_global`, `test_build_host_url_regional`
- Code formatted and linted: `cargo fmt --check` ✓, `./scripts/clippy-lint.sh` ✓

**Manual Live Testing (100% Working):**
Built release binary and tested with actual GCP Vertex AI API:
- ✅ `gemini-3-flash-preview` with `GCP_LOCATION=global` - **SUCCESS**
  - Question: "What is the capital of France?"
  - Response: "Paris" (correct)
  - Confirms global endpoint URL works: `https://aiplatform.googleapis.com`
- ✅ `gemini-3-pro-preview` with `GCP_LOCATION=global` - **SUCCESS**
  - Question: "What is 5 times 7?"
  - Response: "35" (correct)
  - Confirms global endpoint URL works for different Gemini 3 model
- ✅ `gemini-2.0-flash-001` with `GCP_LOCATION=us-central1` - **SUCCESS**
  - Question: "What is 2+2?"
  - Response: "4" (correct)
  - Baseline verification that regional endpoints still work

**Verification:**
- No 404 errors (which would indicate wrong URL construction)
- Responses stored in session database confirm successful API calls
- Both Gemini 3 models now work with global endpoint (previously failed)

### Related Issues
Fixes #6186

## Changes
- Added `GcpLocation::Global` variant with `is_global()` helper method
- Added `build_host_url()` method to handle global vs regional URL construction:
  - Global: `https://aiplatform.googleapis.com`
  - Regional: `https://{location}-aiplatform.googleapis.com`
- Removed `known_location()` method and fallback retry logic (simplification)
- Removed `TryFrom<&str>` impl for `GcpLocation` (no longer needed)

## Impact
- Net -34 lines (92 removed, 58 added)
- Only 2 files modified: `crates/goose/src/providers/formats/gcpvertexai.rs`, `crates/goose/src/providers/gcpvertexai.rs`
- No breaking changes

### CODE REVIEW

File: crates/goose/src/providers/formats/gcpvertexai.rs [hunk 1]
```diff
@@ -17,25 +17,23 @@ pub enum GcpLocation {
     Iowa,
     /// Represents the us-east5 region in Ohio
     Ohio,
+    /// Represents the global endpoint (required for Gemini 3 models)
+    Global,
+}
+
+impl GcpLocation {
+    /// Returns true if this is the global endpoint
+    pub fn is_global(&self) -> bool {
```
Comment (katzdave) [inline crates/goose/src/providers/formats/gcpvertexai.rs]: This function seems unnecessary. We can just check directly against the enum.

File: crates/goose/src/providers/formats/gcpvertexai.rs [hunk 2]
```diff
@@ -461,9 +409,22 @@ mod tests {
...
             }
             assert_eq!(model.to_string(), model_id);
-            assert_eq!(model.known_location(), GcpLocation::Iowa);
         }
 
         Ok(())
     }
+
+    #[test]
+    fn test_gcp_location_display() {
```
Comment (katzdave) [inline crates/goose/src/providers/formats/gcpvertexai.rs]: rm test, just directly mirrors the code.

File: crates/goose/src/providers/formats/gcpvertexai.rs [hunk 3]
```diff
@@ -461,9 +409,22 @@ mod tests {
...
+        assert_eq!(GcpLocation::Iowa.to_string(), "us-central1");
+        assert_eq!(GcpLocation::Ohio.to_string(), "us-east5");
+        assert_eq!(GcpLocation::Global.to_string(), "global");
+    }
+
+    #[test]
+    fn test_gcp_location_is_global() {
```
Comment (katzdave) [inline crates/goose/src/providers/formats/gcpvertexai.rs]: And here

File: crates/goose/src/providers/gcpvertexai.rs [hunk 4]
```diff
@@ -163,6 +163,18 @@ impl GcpVertexAIProvider {
             .unwrap_or_else(|| Iowa.to_string()))
     }
 
+    /// Builds the host URL for the given location.
+    ///
+    /// For the global endpoint, returns `https://aiplatform.googleapis.com`.
```
Comment (katzdave) [inline crates/goose/src/providers/gcpvertexai.rs]: Don't need the comment here at all; function is very concise + clear name.

File: crates/goose/src/providers/gcpvertexai.rs [hunk 5]
```diff
@@ -638,4 +625,22 @@ mod tests {
         // Should contain the original 2 config keys plus 4 new retry-related ones
         assert_eq!(metadata.config_keys.len(), 6);
     }
+
+    #[test]
+    fn test_build_host_url_regional() {
```
Comment (katzdave) [inline crates/goose/src/providers/gcpvertexai.rs]: Rm test

File: crates/goose/src/providers/gcpvertexai.rs [hunk 6]
```diff
@@ -638,4 +625,22 @@ mod tests {
...
+
+        let host = GcpVertexAIProvider::build_host_url("us-east5");
+        assert_eq!(host, "https://us-east5-aiplatform.googleapis.com");
+
+        let host = GcpVertexAIProvider::build_host_url("europe-west1");
+        assert_eq!(host, "https://europe-west1-aiplatform.googleapis.com");
+    }
+
+    #[test]
+    fn test_build_host_url_global() {
```
Comment (katzdave) [inline crates/goose/src/providers/gcpvertexai.rs]: rm test

**Review by katzdave — COMMENTED** [review]
Nice work!

File: crates/goose/src/providers/formats/gcpvertexai.rs (hunk 1 above)
Comment (clouatre) [reply crates/goose/src/providers/formats/gcpvertexai.rs]: Resolved in commit 6800bfc0: Removed `is_global()` method and the empty impl block.

File: crates/goose/src/providers/formats/gcpvertexai.rs (hunk 2 above)
Comment (clouatre) [reply crates/goose/src/providers/formats/gcpvertexai.rs]: Resolved in commit 6800bfc0: Removed test_gcp_location_display test.

File: crates/goose/src/providers/formats/gcpvertexai.rs (hunk 3 above)
Comment (clouatre) [reply crates/goose/src/providers/formats/gcpvertexai.rs]: Resolved in commit 6800bfc0: Removed test_gcp_location_is_global test.

File: crates/goose/src/providers/gcpvertexai.rs (hunk 4 above)
Comment (clouatre) [reply crates/goose/src/providers/gcpvertexai.rs]: Resolved in commit 6800bfc0: Removed the comment block.

File: crates/goose/src/providers/gcpvertexai.rs (hunk 5 above)
Comment (clouatre) [reply crates/goose/src/providers/gcpvertexai.rs]: Resolved in commit 6800bfc0: Removed test_build_host_url_regional test.

File: crates/goose/src/providers/gcpvertexai.rs (hunk 6 above)
Comment (clouatre) [reply crates/goose/src/providers/gcpvertexai.rs]: Resolved in commit 6800bfc0: Removed test_build_host_url_global test.

**Comment by clouatre** [comment]
Thanks @katzdave for the review! All feedback addressed in the latest commit - simplified by removing the `is_global()` helper, the doc comment, and consolidating the test coverage. Appreciate the guidance on keeping the code lean.

**Comment by clouatre** [comment]
Rebased onto main to resolve conflicts with #6191 (streaming support). Ready for merge.

**Comment by clouatre** [comment]
CI failure is due to a pre-existing broken test in main (`code_execution_extension.rs`). This is unrelated to my changes (which only touch `gcpvertexai.rs` files) and is being fixed in #6510. Once #6510 merges, I'll rebase and CI will pass.

File: crates/goose/src/providers/formats/gcpvertexai.rs [hunk 7]
```diff
@@ -29,25 +29,16 @@ pub enum GcpLocation {
     Iowa,
     /// Represents the us-east5 region in Ohio
     Ohio,
+    /// Represents the global endpoint (required for Gemini 3 models)
```
[the remark this answers is not in the document]
Comment (clouatre) [reply crates/goose/src/providers/formats/gcpvertexai.rs:32]: Addressed: Expanded the doc comment to explain why Gemini 3 models require the global endpoint and what errors occur with regional endpoints.

File: crates/goose/src/providers/gcpvertexai.rs [hunk 8]
```diff
@@ -228,6 +228,14 @@ impl GcpVertexAIProvider {
             .unwrap_or_else(|| Iowa.to_string()))
     }
 
+    fn build_host_url(location: &str) -> String {
+        if location == "global" {
+            "https://aiplatform.googleapis.com".to_string()
+        } else {
+            format!("https://{}-aiplatform.googleapis.com", location)
+        }
+    }
```
[the remark this answers is not in the document]
Comment (clouatre) [reply crates/goose/src/providers/gcpvertexai.rs:235]: Addressed: Changed to `location.eq_ignore_ascii_case("global")` to handle case variations like 'Global' or 'GLOBAL'.

File: crates/goose/src/providers/formats/gcpvertexai.rs (hunk 7 above)
[the remark this answers is not in the document]
Comment (clouatre) [reply crates/goose/src/providers/formats/gcpvertexai.rs:32]: Copilot doesn't know about Gemini 3 apparently. Our implementation is correct. We dismiss this suggestion.

**Comment by clouatre** [comment]
Rebased onto latest main following fixes in #6512. CI now passing.

**Comment by katzdave** [comment]
@clouatre Following back up here, seems like 1 more merge conflict, but otherwise would be great to merge!

**Comment by clouatre** [comment]
@katzdave Rebased and resolved the conflict. Also fixed `KNOWN_MODELS` to use the correct model names (`gemini-3-pro-preview` and `gemini-3-flash-preview`). CI is green - ready to merge!

**Comment by cjfit** [comment]
For anyone wondering why this isn't working: the latest release of Goose (1.2.1) does not have this fix baked in. I built from source (main branch) and confirmed this was resolved. Hopefully it's included in 1.2.2
