### PR TITLE
fix: lazy provider creation for goose acp (#7026)

### LINKED ISSUE #7026: goose acp: fails ACP registry CI — missing authMethods and crashes without provider config
## Summary

The [ACP Registry PR #23](https://github.com/agentclientprotocol/registry/pull/23) to add goose to the ACP registry is failing CI because of two issues in `goose acp`.

**Failed CI run:** https://github.com/agentclientprotocol/registry/actions/runs/21552882501/job/62129109237?pr=23

## Issue 1: `GooseAcpAgent::new()` crashes without provider config

The registry CI runs `goose acp` in a sandboxed environment with `HOME` set to an empty temp directory. `GooseAcpAgent::new()` in `crates/goose-acp/src/server.rs` calls `Config::global().get_goose_provider()` which fails because there is no config file. The error propagates via `?` and the process exits **before the stdio JSON-RPC transport is set up**, causing the CI to see a 60-second timeout with no response.

```
✗ Failed: Timeout after 60s waiting for initialize response
```

9 out of 10 other agents in the registry pass this check. Only goose fails.

**Expected behavior:** `goose acp` should still be able to respond to the `initialize` JSON-RPC handshake even when no LLM provider is configured. The provider/model is not needed to respond to `initialize` — it is only needed when actually running a session.

**Suggested fix:** Defer provider creation to session start time rather than during `GooseAcpAgent::new()`, or handle the missing config gracefully so the JSON-RPC transport can still start and respond to `initialize`.

## Issue 2: `on_initialize()` does not return `authMethods`

Even if Issue 1 is fixed, the `on_initialize()` method in `crates/goose-acp/src/server.rs` builds an `InitializeResponse` without any `authMethods`:

```rust
Ok(InitializeResponse::new(args.protocol_version).agent_capabilities(capabilities))
```

The ACP registry CI validator expects at least one `authMethods` entry with type `"agent"` or `"terminal"` in the initialize response. Without this, the validation fails with:

```
No authMethods in response
```

Goose already handles `AuthenticateRequest`/`AuthenticateResponse`, so it does support auth — it just does not advertise it during initialization.

**Suggested fix:** Add auth methods to the `InitializeResponse`. The `agent-client-protocol-schema` crate's `InitializeResponse` struct has an `auth_methods` field, and `AuthMethod` has `id`, `name`, `description`, and `_meta` fields.

## Affected Code

- `crates/goose-acp/src/server.rs`
  - `GooseAcpAgent::new()` (~line 280) — provider/model config required at construction time
  - `on_initialize()` (~line 677) — no `auth_methods` in response

## References

- **ACP Registry PR:** https://github.com/agentclientprotocol/registry/pull/23
- **CI failure:** https://github.com/agentclientprotocol/registry/actions/runs/21552882501/job/62129109237?pr=23
- **CI validator source:** https://github.com/agentclientprotocol/registry/blob/main/.github/workflows/client.py

### PR DESCRIPTION
**Pull request by codefromthecrypt**
## Summary

Before, `goose acp` crashes on startup when there is not yet Goose configuration.

This PR makes provider creation lazy until an ACP session needs it.

This also adds missing ACP `authMethods` is added to the `initialize` response so ACP clients can prompt for setup.

### Type of Change
- [x] Bug fix

### AI Assistance
- [x] This PR was created or reviewed with AI assistance

### Testing

- New `test_initialize_without_provider` test verifies configuration isn't required to initialize ACP.

- ACP registry validation against local build:

```bash
cargo build --release -p goose-cli

# Check out the registry PR that adds goose
cd ../registry
gh pr checkout 23
rm -rf .sandbox /tmp/empty-goose-home && mkdir -p /tmp/empty-goose-home

# Place binary and dummy archive so the verifier skips the download
mkdir -p .sandbox/binary/goose/extracted
cp ../goose-2/target/release/goose .sandbox/binary/goose/extracted/goose
touch .sandbox/binary/goose/goose-aarch64-apple-darwin.tar.bz2

# Run the same auth check the registry CI runs, pointing to an empty directory
GOOSE_PATH_ROOT=/tmp/empty-goose-home uv run --python 3.12 .github/workflows/verify_agents.py --agent goose --auth-check
```

Example output:
```bash
$ ± |add-goose-agent ✓| → GOOSE_PATH_ROOT=/tmp/empty-goose-home uv run --python 3.12 .github/workflows/verify_agents.py --agent goose --auth-check                     
Platform: darwin-aarch64
Registry: /Users/codefromthecrypt/oss/registry
Sandbox:  /Users/codefromthecrypt/oss/registry/.sandbox

Found 10 agents

Verifying 1 agent(s): goose

[1/1] goose (binary)
  Testing binary...
    → Auth check: /Users/codefromthecrypt/oss/registry/.sandbox/binary/goose/extracted/goose acp...
    ✓ Success: Auth OK: goose-provider(agent)
    Sandbox: /Users/codefromthecrypt/oss/registry/.sandbox/binary/goose

==================================================
Summary
==================================================
  Passed:  1
  Failed:  0
  Skipped: 0

All tests passed!

Sandboxes available at: /Users/codefromthecrypt/oss/registry/.sandbox
```

### Related Issues

Fixes #7026
Unblocks https://github.com/agentclientprotocol/registry/pull/23

### CODE REVIEW

File: crates/goose-acp/src/server.rs [hunk 1]
```diff
@@ -692,7 +653,15 @@ impl GooseAcpAgent {
...
             .mcp_capabilities(McpCapabilities::new().http(true));
-        Ok(InitializeResponse::new(args.protocol_version).agent_capabilities(capabilities))
+        Ok(InitializeResponse::new(args.protocol_version)
+            .agent_capabilities(capabilities)
+            .auth_methods(vec![AuthMethod::new(
+                "goose-provider",
+                "Configure Provider",
+            )
+            .description(
+                "Run `goose configure` to set up your AI provider and API key",
```
Comment (codefromthecrypt) [inline crates/goose-acp/src/server.rs:664]: FYI The pattern: id is a slug identifying the auth method, name is a short action label, description tells the user what to do.

```  ┌─────────────────┬────────────────┬──────────────────────────┬───────────────────────────────────────────┐
  │      Agent      │       id       │           name           │                description                │                                                     
  ├─────────────────┼────────────────┼──────────────────────────┼───────────────────────────────────────────┤      
  │ claude-code-acp │ claude-login   │ Log in with Claude Code  │ Run `claude /login` in the terminal       │                                                     
  ├─────────────────┼────────────────┼──────────────────────────┼───────────────────────────────────────────┤      
  │ codex-acp       │ chatgpt        │ Login with ChatGPT       │ Use your ChatGPT login...                 │
  ├─────────────────┼────────────────┼──────────────────────────┼───────────────────────────────────────────┤
  │ codex-acp       │ codex-api-key  │ Use CODEX_API_KEY        │ Requires setting the env var              │
  ├─────────────────┼────────────────┼──────────────────────────┼───────────────────────────────────────────┤
  │ codex-acp       │ openai-api-key │ Use OPENAI_API_KEY       │ Requires setting the env var              │
  ├─────────────────┼────────────────┼──────────────────────────┼───────────────────────────────────────────┤
  │ cursor-acp      │ cursor-login   │ Log in with Cursor Agent │ Run `cursor-agent login` in your terminal │
  ├─────────────────┼────────────────┼──────────────────────────┼───────────────────────────────────────────┤
  │ qwen-code       │ USE_OPENAI     │ Use OpenAI API key       │ Requires setting OPENAI_API_KEY           │
  ├─────────────────┼────────────────┼──────────────────────────┼───────────────────────────────────────────┤
  │ qwen-code       │ QWEN_OAUTH     │ Qwen OAuth               │ OAuth authentication for Qwen models      │
  ├─────────────────┼────────────────┼──────────────────────────┼───────────────────────────────────────────┤
  │ mistral-vibe    │ vibe-setup     │ Register your API Key    │ Register your API Key inside Mistral Vibe │
  └─────────────────┴────────────────┴──────────────────────────┴───────────────────────────────────────────┘
```

**Review by alexhancock — APPROVED** [review]
