### PR TITLE
Fix YAML serialization for recipes with special characters

### LINKED ISSUE #5508: UI recipe saving fails if invalid yaml in instructions or other fields
**Describe the bug**

If you save recipe details from the UI with invalid yaml it fails with syntax error.

- No colons in the middle of lines (which can be interpreted as YAML)
- No special characters like {}, #, ---
- No complex formatting
- Simplified language while keeping all the essential instructions

**Expected behavior**
Should allow saving anything and make it work in the yaml file

**Screenshots**

Image

**Please provide following information:**
 - **OS & Arch:** Mac Arm
 - **Interface:** UI
 - **Version:** v1.12.1
 - **Extensions enabled:** Developer
 - **Provider & Model:** Claude

**Additional context**

### PR DESCRIPTION
**Pull request by JJSwigut**
Fixes #5508

When saving recipes from the UI, fields containing YAML special characters (colons, hashes, braces, etc.) were causing syntax errors because the serialization wasn't properly handling these characters.

## Changes
- Uses `Recipe::to_yaml()` instead of `serde_yaml::to_string()` in `save_recipe_to_file()`
- The `to_yaml()` method applies proper formatting and handles multiline values
- Removes unused validation code from the UI that was never called
- Adds comprehensive tests for special character handling

## Why This Fixes the Issue
The `Recipe::to_yaml()` method uses `serde_yaml` with additional formatting via `reformat_fields_with_multiline_values()` which ensures proper quoting and escaping of special characters, especially in multiline contexts.

Users can now save recipes with any content in the UI fields without encountering YAML syntax errors.

### CODE REVIEW

File: ui/desktop/src/recipe/recipe_management.ts [hunk 1]
```diff
@@ -1,4 +1,9 @@
-import { Recipe, saveRecipe as saveRecipeApi, listRecipes, RecipeManifestResponse } from '../api';
+import {
+  Recipe,
+  saveRecipe as saveRecipeApi,
+  listRecipes,
+  RecipeManifestResponse,
+} from '../api';
```
Comment (DOsinga) [inline ui/desktop/src/recipe/recipe_management.ts]: did anything change here?

File: crates/goose/src/recipe/mod.rs [hunk 2]
```diff
@@ -772,4 +772,70 @@ isGlobal: true"#;
             panic!("Expected Stdio extension");
         }
     }
+
+    #[test]
```
Comment (DOsinga) [inline crates/goose/src/recipe/mod.rs]: delete these tests.

**Review by DOsinga — APPROVED** [review]

File: ui/desktop/src/recipe/recipe_management.ts (hunk 1 above)
Comment (JJSwigut) [reply ui/desktop/src/recipe/recipe_management.ts]: ran the formatter and I think this was just a long line

**Comment by JJSwigut** [comment]
@DOsinga I never saw the button to merge this? am i missing a part of the process?

**Comment by zanesq** [comment]
@JJSwigut can you do the DCO sign-off step and I'll merge it for you

**Comment by michaelneale** [comment]
is there a way to override the DCO for such a small change? as would be good to have it

**Review by alexhancock — APPROVED** [review]

**Comment by alexhancock** [comment]
@michaelneale I just merged it. Thanks @JJSwigut
