### PR TITLE
Fix max turns configuration

### LINKED ISSUE #7609: Agent turn limits configuration not working
**Describe the bug**

GOOSE_MAX_TURNS and GOOSE_SUBAGENT_MAX_TURNS are not respected in the config.yaml. 

GOOSE_SUBAGENT_MAX_TURNS is only respected as an environment variable

The only way to set the main agent max turns is to use --max-turns as a cli flag. The GOOSE_MAX_TURNS usage as an environment variable doesn't work.

Using an AI agent gathered these bugs and I confirmed that these are bugs by manually invoking the cli tool and saw the turn limit not functioning correctly

### PR DESCRIPTION
**Pull request by alexyao2015**
## Summary
Fixes #7609

### Type of Change

- [ ] Feature
- [x] Bug fix
- [ ] Refactor / Code quality
- [ ] Performance improvement
- [ ] Documentation
- [ ] Tests
- [ ] Security fix
- [ ] Build / Release
- [ ] Other (specify below)

### AI Assistance

- [x] This PR was created or reviewed with AI assistance

### Related Issues
Relates to #7609
Discussion: LINK (if any)

### CODE REVIEW

File: crates/goose/src/agents/platform_extensions/summon.rs [hunk 1]
```diff
@@ -1512,6 +1511,7 @@ impl SummonClient {
     }
 
     fn resolve_max_turns(&self, session: &crate::session::Session) -> usize {
+        // Priority: env var > recipe settings > config.yaml > default
```
Comment (jamadeo) [inline crates/goose/src/agents/platform_extensions/summon.rs:1514]: I'm not totally sure that this is the right sequence, but I can't think of a better one. Given that the env var is currently taking precedent over the recipe setting, I think this is probably the best option.
