### PR TITLE
Desktop: - No Custom Headers field for custom OpenAI-compatible providers 

### LINKED ISSUE #6048: Desktop: No Custom Headers field for custom OpenAI-compatible providers
**Describe the bug**

Desktop UI does not provide a way to configure custom headers for OpenAI-compatible custom providers. CLI supports this feature, but Desktop users have no equivalent option.

---

**To Reproduce**
1. Open goose Desktop > Settings > Models > Configure providers
2. Click `Add Custom Provider`
3. Select `OpenAI Compatible` as the Provider Type
4. Observe that there is no field for custom headers
5. Compare with CLI: run `goose configure` > `Custom Providers` > `Add A Custom Provider` > `OpenAI Compatible` where you're prompted to add custom headers

---

**Expected behavior**
Desktop should provide a way to configure/view/edit custom headers for OpenAI-compatible custom providers, matching CLI functionality.

---

**Screenshots**
N/A

---

**Please provide the following information**
- **OS & Arch:** macOS
- **Interface:** UI (goose Desktop)
- **Version:** v1.16.0
- **Extensions enabled:** N/A
- **Provider & Model:** Custom OpenAI-compatible provider

---

**Additional context**
PR #5017 added backend support for custom headers, including:
- `UpdateCustomProviderRequest` includes `headers` field
- `openapi.json` and `types.gen.ts` have the schema
- CLI flow works correctly

Fix: Add a headers input field to `CustomProviderForm.tsx` that captures and submits headers using the existing backend support.

### PR DESCRIPTION
**Pull request by Lymah123**
## Summary

This PR:
-  Add custom headers section to CustomProviderForm with add/remove/edit functionality
- Fix modal scrolling issue by adding max-h and overflow-y-auto to DialogContent
- Fix duplicate isFilePickerOpen declaration in ChatInput.tsx
- Update auto-generated API client files
### Type of Change

- [x] Feature
- [ ] Bug fix
- [ ] Refactor / Code quality
- [ ] Performance improvement
- [ ] Documentation
- [ ] Tests
- [ ] Security fix
- [ ] Build / Release
- [ ] Other (specify below)

### AI Assistance

- [ ] This PR was created or reviewed with AI assistance

### Related Issues
closes #6048  
Discussion: LINK (if any)

### Screenshots/Demos (for UX changes)
Before:  

After:   

Screenshot (75)

### CODE REVIEW

**Comment by zanesq** [comment]
Thanks, does the goose backend actually use these new header fields in the LLM requests?

**Comment by Lymah123** [comment]
> Thanks, does the goose backend actually use these new header fields in the LLM requests?

Yes, the backend fully supports and uses custom headers. In `openai.rs` (lines 169-177), the `from_custom_config` method reads headers from `DeclarativeProviderConfig`, converts them to a `HeaderMap`, and adds them to the `ApiClient`. These headers are then included in all HTTP requests to the custom provider. The UI was simply missing a way to set these headers - the backend has supported them all along.

Moreover, this feature is already in CLI.

**Comment by Lymah123** [comment]
The PR is ready for review.

File: crates/goose/src/config/declarative_providers.rs [hunk 1]
```diff
@@ -170,7 +172,7 @@ pub fn update_custom_provider(
             api_key_env: existing_config.api_key_env,
             base_url: api_url,
             models: model_infos,
-            headers: existing_config.headers,
+            headers: headers.or(existing_config.headers),
```
Comment (zanesq) [inline crates/goose/src/config/declarative_providers.rs]: I think this logic means:

If headers is Some(...), use the new headers
If headers is None, keep existing headers

This makes it impossible to clear headers once set. If a user wants to remove all custom headers, passing None will just keep the old ones.

Maybe the UI should distinguish between "not provided" and "explicitly empty"?

change to something like
```
headers: if headers.is_some() { headers } else { existing_config.headers },
// Or better: always use the provided headers value (including None to clear)
headers: headers,
```
And update the UI to explicitly send {} when user wants no headers.

File: crates/goose/src/config/declarative_providers.rs [hunk 2]
```diff
@@ -133,6 +133,7 @@ pub fn create_custom_provider(
     Ok(provider_config)
 }
 
+#[allow(clippy::too_many_arguments)]
```
Comment (zanesq) [inline crates/goose/src/config/declarative_providers.rs]: The function now has 8 parameters. 
Rather than adding the clippy allow maybe create a struct like UpdateCustomProviderParams to group these? This would also make future additions cleaner.

File: ui/desktop/src/components/settings/providers/modal/subcomponents/forms/CustomProviderForm.tsx [hunk 3]
```diff
@@ -71,13 +133,24 @@ export default function CustomProviderForm({
...
+    );
+
     onSubmit({
       engine,
       display_name: displayName,
       api_url: apiUrl,
       api_key: apiKey,
       models: modelList,
       supports_streaming: supportsStreaming,
+      headers: Object.keys(headersObject).length > 0 ? headersObject : null,
```
[the remark this answers is not in the document]
Comment (zanesq) [reply ui/desktop/src/components/settings/providers/modal/subcomponents/forms/CustomProviderForm.tsx]: @Lymah123 can you review these copilot reviews and resolve or comment?

File: crates/goose/src/config/declarative_providers.rs (hunk 1 above)
Comment (Lymah123) [reply crates/goose/src/config/declarative_providers.rs]: Alright, I'd do that. Thanks.

**Comment by Lymah123** [comment]
Thanks for the feedback and the suggestions @zanesq . I will look into that. Yes, I will resolve the Copilot reviews. I was waiting for human reviews and working on the suggestions together.

File: crates/goose-cli/src/session/builder.rs [hunk 4]
```diff
@@ -542,9 +542,15 @@ pub async fn build_session(session_config: SessionBuilderConfig) -> CliSession {
...
+    let streamable_urls: Vec<String> = session_config
+        .streamable_http_extensions
+        .iter()
+        .map(|opt| opt.url.clone())
+        .collect();
+
     let cli_flag_extensions_to_load = parse_cli_flag_extensions(
         &session_config.extensions,
-        &session_config.streamable_http_extensions,
+        &streamable_urls,
```
[the remark this answers is not in the document]
Comment (Lymah123) [reply crates/goose-cli/src/session/builder.rs]: fixed

File: crates/goose-server/src/routes/config_management.rs [hunk 5]
```diff
@@ -747,6 +747,8 @@ pub async fn update_custom_provider(
             requires_auth: request.requires_auth,
         },
     )?;
+    .map_err(|_| StatusCode::INTERNAL_SERVER_ERROR)?;
+>>>>>>> 04269837bc8 (Backend: Add headers parameter to update_custom_provider)
```
[the remark this answers is not in the document]
Comment (Lymah123) [reply crates/goose-server/src/routes/config_management.rs]: Fixed

**Comment by Lymah123** [comment]
Waiting for review on this PR!

**Comment by zanesq** [comment]
Thanks will take a look today wrapping up some stuff

File: ui/desktop/src/components/ChatInput.tsx [hunk 6]
```diff
@@ -1636,4 +1632,4 @@ export default function ChatInput({
       </div>
     </div>
   );
-}
+}
```
Comment (zanesq) [inline ui/desktop/src/components/ChatInput.tsx]: pls add the newline back

**Comment by Lymah123** [comment]
> @Lymah123 looking better thanks! I think a few more things from copilot are left unresolved and seem worthy of fixing.
> 
> 1. **Duplicate header key validation** - Add check in handleAddHeader to prevent adding headers with keys that already exist
> 2. **Header edit validation** - Add validation in handleHeaderChange or on form submit to catch invalid edits
> 3. **Cannot clear headers** - Change the logic so passing None or empty object clears headers, or update UI to send explicit empty object {} when user wants no headers

@zanesq, I have made the requested changes. Thanks!

**Comment by Lymah123** [comment]
> > @Lymah123 looking better thanks! I think a few more things from copilot are left unresolved and seem worthy of fixing.
> > 
> > 1. **Duplicate header key validation** - Add check in handleAddHeader to prevent adding headers with keys that already exist
> > 2. **Header edit validation** - Add validation in handleHeaderChange or on form submit to catch invalid edits
> > 3. **Cannot clear headers** - Change the logic so passing None or empty object clears headers, or update UI to send explicit empty object {} when user wants no headers
> 
> @zanesq, I have made the requested changes. Thanks!

Hello @zanesq !

**Comment by zanesq** [comment]
@Lymah123 apologies been real busy, can you pull in main and resolve the conflicts then I will do some more testing on this

**Comment by Lymah123** [comment]
@zanesq fixed!

**Review by zanesq — APPROVED** [review]
@Lymah123 thanks! I tested locally and pushed some minor fixes and cleanup LGTM.
