### PR TITLE
fix: message summary incorrectly generated

### LINKED ISSUE #1524: False Rate Limit Error Messages
**Describe the bug**

### Description
Goose is displaying rate limit error messages from the Anthropic API despite normal network traffic and request sizes. The error appears to be a false positive as the network monitoring shows no signs of excessive requests or payload sizes.

**To Reproduce**
1. Normal interaction with Goose
2. Error appears in responses despite:
   - Normal network traffic (verified in browser dev tools)
   - No excessive request sizes
   - No actual rate limiting from the API

**Expected behavior**
- Rate limit errors should only appear when actually hitting API rate limits
- Error messages should accurately reflect the actual state of API interactions

**Screenshots**

Image

**Please provide following information:**
 - **OS & Arch:** macOS 14.1.1 (ARM64)
 - **Interface:** UI
 - **Version:**  1.0.12
 - **Extensions enabled:** Developer
 - **Provider & Model:** Anthropic claude-3-5-sonnet-latest

**Additional context**

### Actual Behavior
- Rate limit errors are being shown when network traffic appears normal
- Messages suggest rate limiting but network monitoring shows no signs of excessive requests

### Error Message
```log
Failed to generate session description: RateLimitExceeded("Some(Object {"error": Object {"message": String("This request would exceed the rate limit for your organization (fe514f84-91b5-4ee2-b5aa-53e0b5820662) of 8,000 output tokens per minute..."), "type": String("rate_limit_error")}, "type": String("error")}")
```

### Additional Notes
- The error appears in logs at: ~/Library/Application Support/Goose/logs/main.log
- Browser network monitoring shows normal request patterns
- Error persists across multiple interactions

### PR DESCRIPTION
**Pull request by bertlebee**
fixes #1524. generate_description wasn't being used. The (mostly duplicated) logic didn't filter for user messages. Sending the whole conversation for summary probably misses the point and burns tokens.

### CODE REVIEW

**Review by wendytang — COMMENTED** [review]
good find - `generate_description` seems not used

**Review by wendytang — CHANGES_REQUESTED** [review]
there are duplicate metadata reads - `read_metadata` occurs once at the top of `persist_messages` and another in `generate_description`

i think the fix would be to replace lines 331-338:
```
    // Read current metadata
    let mut metadata = read_metadata(session_file)?;

    // Update description
    metadata.description = description;

    // Update the file with the new metadata and existing messages
    update_metadata(session_file, &metadata).await?;
```

with 

```
    // Write the file with metadata and messages
    save_messages_with_metadata(session_file, &metadata, messages)
```

File: crates/goose/src/session/storage.rs [hunk 1]
```diff
@@ -323,12 +293,19 @@ pub async fn generate_description(
...
+    // get context from messages so far, limiting each message to 300 chars
     let context: Vec<String> = messages
         .iter()
         .filter(|m| m.role == mcp_core::role::Role::User)
         .take(3) // Use up to first 3 user messages for context
-        .map(|m| m.as_concat_text())
+        .map(|m| {
+            let text = m.as_concat_text();
+            if text.len() > 300 {
+                format!("{}...", &text[..297]) // truncate to 300 chars with ellipsis
```
Comment (bertlebee) [inline crates/goose/src/session/storage.rs]: do we need to truncate the user messages? 900 (300 x 3 messages) chars isn't a lot of tokens and I'm sure quite a few of my prompts are well over 300 chars.  The rate limit I've been hitting is [Input Tokens Per Min](https://docs.anthropic.com/en/api/rate-limits#rate-limits) (20k on Sonnet 3.7 at Tier 1).

(for context, the previous paragraph is 306 chars)

**Comment by bertlebee** [comment]
> there are duplicate metadata reads - `read_metadata` occurs once at the top of `persist_messages` and another in `generate_description`
well spotted! more importantly, there were duplicate metadata writes, and the updated description would have been clobbered!
> 
> i think the fix would be to replace lines 331-338:
> 
> ```
>     // Read current metadata
>     let mut metadata = read_metadata(session_file)?;
> 
>     // Update description
>     metadata.description = description;
> 
>     // Update the file with the new metadata and existing messages
>     update_metadata(session_file, &metadata).await?;
> ```
> 
> with
> 
> ```
>     // Write the file with metadata and messages
>     save_messages_with_metadata(session_file, &metadata, messages)
> ```
We can't do this without changing the method signature (I'm not sure if breaking changes to public functions are ok at this point) because `generate_description` doesn't have access to the metadata without reading it from the file. I've changed it so that the metadata is only read (and subsequently written) in persist_messages if we've decided not to update the description and want to write the file with the existing metadata.

It's ugly but I think it should work :)

File: crates/goose/src/session/storage.rs [hunk 2]
```diff
@@ -358,9 +335,7 @@ pub async fn generate_description(
     metadata.description = description;
 
     // Update the file with the new metadata and existing messages
-    update_metadata(session_file, &metadata).await?;
-
-    Ok(())
+    return save_messages_with_metadata(session_file, &metadata, messages);
```
Comment (bertlebee) [inline crates/goose/src/session/storage.rs]: unrelated rust noob question, why do I need the explicit return statement here? `update_metadata` has the same return type but doesn't have an explicit return, even though the last line is a call to `save_messages_with_metadata`, just like here (line 347). without this return, I get ` expected enum `Result<(), anyhow::Error>`found unit type `()``

Comment (bertlebee) [reply crates/goose/src/session/storage.rs]: Nvm, I figured it out, it's the semicolon! I guess that makes sense.

File: crates/goose/src/session/storage.rs (hunk 1 above)
Comment (wendytang) [reply crates/goose/src/session/storage.rs]: Yeah maybe it is too few characters - I removed it.

**Comment by bertlebee** [comment]
@wendytang anything else needed to get this merged?

**Review by wendytang — APPROVED** [review]

**Comment by bertlebee** [comment]
Thanks @wendytang and @kalvinnchau :)
