### PR TITLE
fix: handle empty arguments in tool call

### LINKED ISSUE #1108: Tool call issues: Memories and developer
**Describe the bug**
Multiple tool call errors while agent carries out a task:
This was the first, when attempting to analyze a file or directory.
{"role":"assistant","created":1738803195,"content":[{"Text":{"text":"\n\nNow, let me check the contract manager implementation:"}},{"ToolRequest":{"id":"toolu_01Xj1kT84A5DUEeCFxYkt8rz","tool_call":{"Err":{"InvalidParameters":"Could not interpret tool use parameters for id toolu_01Xj1kT84A5DUEeCFxYkt8rz: EOF while parsing a value at line 1 column 0"}}}}]}

The second was telling Goose to analyze my project directory and add relevant memories across sessions in different categories. Sonnet tried to add multiple memories one at a time and eventually was blocked by this error:
{"role":"assistant","created":1738802964,"content":[{"Text":{"text":"\n\nBased on my analysis, I'll store several relevant memories about this project. Let me add them one by one:"}},{"ToolRequest":{"id":"toolu_011UCY9r5FGDgKD28i2z6moJ","tool_call":{"Ok":{"name":"memory__remember_memory","arguments":{"category":"project_setup","data":"This is a Poetry-managed Python project for SpaceTraders game automation. Python version requirement: ^3.9","is_global":false,"tags":["poetry","python","dependencies"]}}}}}]}
{"role":"user","created":1738802964,"content":[{"ToolResponse":{"id":"toolu_011UCY9r5FGDgKD28i2z6moJ","tool_result":{"Ok":[{"type":"text","text":"Stored memory in category: project_setup"}]}}}]}
{"role":"assistant","created":1738802971,"content":[{"Text":{"text":""}},{"ToolRequest":{"id":"toolu_015DUKyd8gBuJyv6J65Dbj6E","tool_call":{"Err":{"InvalidParameters":"Could not interpret tool use parameters for id toolu_015DUKyd8gBuJyv6J65Dbj6E: EOF while parsing a value at line 1 column 0"}}}}]}

**To Reproduce**
1. Go to 'start a new Goose session'
2. Invoke the memory tool like I did and ask Goose to analyze a project structure and create memories for it.'
3. 'The tool may add one or two memories, but eventually terminate with an End of File value error.'
4. See error:
{"role":"assistant","created":1738802964,"content":[{"Text":{"text":"\n\nBased on my analysis, I'll store several relevant memories about this project. Let me add them one by one:"}},{"ToolRequest":{"id":"toolu_011UCY9r5FGDgKD28i2z6moJ","tool_call":{"Ok":{"name":"memory__remember_memory","arguments":{"category":"project_setup","data":"This is a Poetry-managed Python project for SpaceTraders game automation. Python version requirement: ^3.9","is_global":false,"tags":["poetry","python","dependencies"]}}}}}]}
{"role":"user","created":1738802964,"content":[{"ToolResponse":{"id":"toolu_011UCY9r5FGDgKD28i2z6moJ","tool_result":{"Ok":[{"type":"text","text":"Stored memory in category: project_setup"}]}}}]}
{"role":"assistant","created":1738802971,"content":[{"Text":{"text":""}},{"ToolRequest":{"id":"toolu_015DUKyd8gBuJyv6J65Dbj6E","tool_call":{"Err":{"InvalidParameters":"Could not interpret tool use parameters for id toolu_015DUKyd8gBuJyv6J65Dbj6E: EOF while parsing a value at line 1 column 0"}}}}]}

**Expected behavior**
The memory tool being able to add memories, including longer context ones such as the readme in the error output.
**Screenshots**

**Please provide following information:**
 - **OS & Arch:** Ubuntu 22.04 x64 (WSL)]
 - **Interface:** [CLI]
 - **Version:** [v1.0.4]
 - **Extensions enabled:** [Computer Controller, Developer, memory]
 - **Provider & Model:** [e.g. Google - gemini-1.5-pro]

**Additional context**
Here is the memory tool MCP log, if that helps.
  2025-02-06T00:46:59.125772Z  INFO goose::commands::mcp: Starting MCP server
    at crates/goose-cli/src/commands/mcp.rs:13

  2025-02-06T00:46:59.129576Z  INFO goose::commands::mcp: Server initialized and ready to handle requests
    at crates/goose-cli/src/commands/mcp.rs:31

  2025-02-06T00:46:59.129584Z  INFO mcp_server: Server started
    at crates/mcp-server/src/lib.rs:138

  2025-02-06T00:46:59.129714Z  INFO mcp_server: incoming message, json: {"jsonrpc":"2.0","id":1,"method":"initialize","params":{"capabilities":{},"clientInfo":{"name":"goose","version":"1.0.4"},"protocolVersion":"1.0.0"}}

    at crates/mcp-server/src/lib.rs:62

  2025-02-06T00:46:59.129732Z  INFO mcp_server: Received request, request_id: Some(1), method: "initialize", json: {"jsonrpc":"2.0","id":1,"method":"initialize","params":{"capabilities":{},"clientInfo":{"name":"goose","version":"1.0.4"},"protocolVersion":"1.0.0"}}
    at crates/mcp-server/src/lib.rs:150
    in mcp_server::message_processing

  2025-02-06T00:46:59.129752Z  INFO mcp_server: Sending response, response_id: Some(1), json: {"jsonrpc":"2.0","id":1,"result":{"capabilities":{"tools":{"listChanged":false}},"instructions":" This extension allows storage and retrieval of categorized information with tagging support. It's designed to help\n manage important information across sessions in a systematic and organized manner.\n Capabilities:\n 1. Store information in categories with optional tags for context-based retrieval.\n 2. Search memories by content or specific tags to find relevant information.\n 3. List all available memory categories for easy navigation.\n 4. Remove entire categories of memories when they are no longer needed.\n When to call memory tools:\n - These are examples where the assistant should proactively call the memory tool because the user is providing recurring preferences, project details, or workflow habits that they may expect to be remembered.\n - Preferred Development Tools & Conventions\n - User-specific data (e.g., name, preferences)\n - Project-related configurations\n - Workflow descriptions\n - Other critical settings\n Interaction Protocol:\n When important information is identified, such as:\n - User-specific data (e.g., name, preferences)\n - Project-related configurations\n - Workflow descriptions\n - Other critical settings\n The protocol is:\n 1. Identify the critical piece of information.\n 2. Ask the user if they'd like to store it for later reference.\n 3. Upon agreement:\n    - Suggest a relevant category like \"personal\" for user data or \"development\" for project preferences.\n    - Inquire about any specific tags they want to apply for easier lookup.\n    - Confirm the desired storage location:\n      - Local storage (.goose/memory) for project-specific details.\n      - Global storage (~/.config/goose/memory) for user-wide data.\n    - Use the remember_memory tool to store the information.\n      - `remember_memory(category, data, tags, is_global)`\n Example Interaction for Storing Information:\n User: \"For this project, we use black for code formatting\"\n Assistant: \"You've mentioned a development preference. Would you like to remember this for future conversations?\n User: \"Yes, please.\"\n Assistant: \"I'll store this in the 'development' category. Any specific tags to add? Suggestions: #formatting\n #tools\"\n User: \"Yes, use those tags.\"\n Assistant: \"Shall I store this locally for this project only, or globally for all projects?\"\n User: \"Locally, please.\"\n Assistant: *Stores the information under category=\"development\", tags=\"formatting tools\", scope=\"local\"*\n Retrieving Memories:\n To access stored information, utilize the memory retrieval protocols:\n - **Search by Category**:\n   - Provides all memories within the specified context.\n   - Use: `retrieve_memories(category=\"development\", is_global=False)`\n   - Note: If you want to retrieve all local memories, use `retrieve_memories(category=\"*\", is_global=False)`\n   - Note: If you want to retrieve all global memories, use `retrieve_memories(category=\"*\", is_global=True)`\n - **Filter by Tags**:\n   - Enables targeted retrieval based on specific tags.\n   - Use: Provide tag filters to refine search.\nTo remove a memory, use the following protocol:\n- **Remove by Category**:\n  - Removes all memories within the specified category.\n  - Use: `remove_memory_category(category=\"development\", is_global=False)`\n  - Note: If you want to remove all local memories, use `remove_memory_category(category=\"*\", is_global=False)`\n  - Note: If you want to remove all global memories, use `remove_memory_category(category=\"*\", is_global=True)`\nThe Protocol is:\n 1. Confirm what kind of information the user seeks by category or keyword.\n 2. Suggest categories or relevant tags based on the user's request.\n 3. Use the retrieve function to access relevant memory entries.\n 4. Present a summary of findings, offering detailed exploration upon request.\n Example Interaction for Retrieving Information:\n User: \"What configuration do we use for code formatting?\"\n Assistant: \"Let me check the 'development' category for any related memories. Searching using #formatting tag.\"\n Assistant: *Executes retrieval: `retrieve_memories(category=\"development\", is_global=False)`*\n Assistant: \"We have 'black' configured for code formatting, specific to this project. Would you like further\n details?\"\n Memory Overview:\n - Categories can include a wide range of topics, structured to keep information grouped logically.\n - Tags enable quick filtering and identification of specific entries.\n Operational Guidelines:\n - Always confirm with the user before saving information.\n - Propose suitable categories and tag suggestions.\n - Discuss storage scope thoroughly to align with user needs.\n - Acknowledge the user about what is stored and where, for transparency and ease of future retrieval.\n\n\n**Here are the user's currently saved memories:**\nPlease keep this information in mind when answering future questions.\nDo not bring up memories unless relevant.\nNote: if the user has not saved any memories, this section will be empty.\nNote: if the user removes a memory that was previously loaded into the system, please remove it from the system instructions.\n","protocolVersion":"2024-11-05","serverInfo":{"name":"memory","version":"0.1.0"}}}
    at crates/mcp-server/src/lib.rs:180
    in mcp_server::message_processing

  2025-02-06T00:46:59.130873Z  INFO mcp_server: incoming message, json: {"jsonrpc":"2.0","method":"notifications/initialized","params":{}}

    at crates/mcp-server/src/lib.rs:62

  2025-02-06T00:47:08.478894Z  INFO mcp_server: incoming message, json: {"jsonrpc":"2.0","id":2,"method":"tools/list","params":{}}

    at crates/mcp-server/src/lib.rs:62

  2025-02-06T00:47:08.478920Z  INFO mcp_server: Received request, request_id: Some(2), method: "tools/list", json: {"jsonrpc":"2.0","id":2,"method":"tools/list","params":{}}
    at crates/mcp-server/src/lib.rs:150
    in mcp_server::message_processing

  2025-02-06T00:47:08.478973Z  INFO mcp_server: Sending response, response_id: Some(2), json: {"jsonrpc":"2.0","id":2,"result":{"tools":[{"description":"Stores a memory with optional tags in a specified category","inputSchema":{"properties":{"category":{"type":"string"},"data":{"type":"string"},"is_global":{"type":"boolean"},"tags":{"items":{"type":"string"},"type":"array"}},"required":["category","data","is_global"],"type":"object"},"name":"remember_memory"},{"description":"Retrieves all memories from a specified category","inputSchema":{"properties":{"category":{"type":"string"},"is_global":{"type":"boolean"}},"required":["category","is_global"],"type":"object"},"name":"retrieve_memories"},{"description":"Removes all memories within a specified category","inputSchema":{"properties":{"category":{"type":"string"},"is_global":{"type":"boolean"}},"required":["category","is_global"],"type":"object"},"name":"remove_memory_category"},{"description":"Removes a specific memory within a specified category","inputSchema":{"properties":{"category":{"type":"string"},"is_global":{"type":"boolean"},"memory_content":{"type":"string"}},"required":["category","memory_content","is_global"],"type":"object"},"name":"remove_specific_memory"}]}}
    at crates/mcp-server/src/lib.rs:180
    in mcp_server::message_processing

  2025-02-06T00:47:53.294173Z  INFO mcp_server: incoming message, json: {"jsonrpc":"2.0","id":3,"method":"tools/list","params":{}}

    at crates/mcp-server/src/lib.rs:62

  2025-02-06T00:47:53.294207Z  INFO mcp_server: Received request, request_id: Some(3), method: "tools/list", json: {"jsonrpc":"2.0","id":3,"method":"tools/list","params":{}}
    at crates/mcp-server/src/lib.rs:150
    in mcp_server::message_processing

  2025-02-06T00:47:53.294263Z  INFO mcp_server: Sending response, response_id: Some(3), json: {"jsonrpc":"2.0","id":3,"result":{"tools":[{"description":"Stores a memory with optional tags in a specified category","inputSchema":{"properties":{"category":{"type":"string"},"data":{"type":"string"},"is_global":{"type":"boolean"},"tags":{"items":{"type":"string"},"type":"array"}},"required":["category","data","is_global"],"type":"object"},"name":"remember_memory"},{"description":"Retrieves all memories from a specified category","inputSchema":{"properties":{"category":{"type":"string"},"is_global":{"type":"boolean"}},"required":["category","is_global"],"type":"object"},"name":"retrieve_memories"},{"description":"Removes all memories within a specified category","inputSchema":{"properties":{"category":{"type":"string"},"is_global":{"type":"boolean"}},"required":["category","is_global"],"type":"object"},"name":"remove_memory_category"},{"description":"Removes a specific memory within a specified category","inputSchema":{"properties":{"category":{"type":"string"},"is_global":{"type":"boolean"},"memory_content":{"type":"string"}},"required":["category","memory_content","is_global"],"type":"object"},"name":"remove_specific_memory"}]}}
    at crates/mcp-server/src/lib.rs:180
    in mcp_server::message_processing

  2025-02-06T00:47:58.763481Z  INFO mcp_server: incoming message, json: {"jsonrpc":"2.0","id":4,"method":"tools/call","params":{"arguments":{"category":"*","is_global":false},"name":"retrieve_memories"}}

    at crates/mcp-server/src/lib.rs:62

  2025-02-06T00:47:58.763504Z  INFO mcp_server: Received request, request_id: Some(4), method: "tools/call", json: {"jsonrpc":"2.0","id":4,"method":"tools/call","params":{"arguments":{"category":"*","is_global":false},"name":"retrieve_memories"}}
    at crates/mcp-server/src/lib.rs:150
    in mcp_server::message_processing

  2025-02-06T00:47:58.766238Z  INFO mcp_server: Sending response, response_id: Some(4), json: {"jsonrpc":"2.0","id":4,"result":{"content":[{"text":"Retrieved memories: {}","type":"text"}]}}
    at crates/mcp-server/src/lib.rs:180
    in mcp_server::message_processing

  2025-02-06T00:48:05.820637Z  INFO mcp_server: incoming message, json: {"jsonrpc":"2.0","id":5,"method":"tools/call","params":{"arguments":{"category":"*","is_global":true},"name":"retrieve_memories"}}

    at crates/mcp-server/src/lib.rs:62

  2025-02-06T00:48:05.820672Z  INFO mcp_server: Received request, request_id: Some(5), method: "tools/call", json: {"jsonrpc":"2.0","id":5,"method":"tools/call","params":{"arguments":{"category":"*","is_global":true},"name":"retrieve_memories"}}
    at crates/mcp-server/src/lib.rs:150
    in mcp_server::message_processing

  2025-02-06T00:48:05.820725Z  INFO mcp_server: Sending response, response_id: Some(5), json: {"jsonrpc":"2.0","id":5,"result":{"content":[{"text":"Retrieved memories: {}","type":"text"}]}}
    at crates/mcp-server/src/lib.rs:180
    in mcp_server::message_processing

  2025-02-06T00:48:51.145427Z  INFO mcp_server: incoming message, json: {"jsonrpc":"2.0","id":6,"method":"tools/list","params":{}}

    at crates/mcp-server/src/lib.rs:62

  2025-02-06T00:48:51.145444Z  INFO mcp_server: Received request, request_id: Some(6), method: "tools/list", json: {"jsonrpc":"2.0","id":6,"method":"tools/list","params":{}}
    at crates/mcp-server/src/lib.rs:150
    in mcp_server::message_processing

  2025-02-06T00:48:51.145476Z  INFO mcp_server: Sending response, response_id: Some(6), json: {"jsonrpc":"2.0","id":6,"result":{"tools":[{"description":"Stores a memory with optional tags in a specified category","inputSchema":{"properties":{"category":{"type":"string"},"data":{"type":"string"},"is_global":{"type":"boolean"},"tags":{"items":{"type":"string"},"type":"array"}},"required":["category","data","is_global"],"type":"object"},"name":"remember_memory"},{"description":"Retrieves all memories from a specified category","inputSchema":{"properties":{"category":{"type":"string"},"is_global":{"type":"boolean"}},"required":["category","is_global"],"type":"object"},"name":"retrieve_memories"},{"description":"Removes all memories within a specified category","inputSchema":{"properties":{"category":{"type":"string"},"is_global":{"type":"boolean"}},"required":["category","is_global"],"type":"object"},"name":"remove_memory_category"},{"description":"Removes a specific memory within a specified category","inputSchema":{"properties":{"category":{"type":"string"},"is_global":{"type":"boolean"},"memory_content":{"type":"string"}},"required":["category","memory_content","is_global"],"type":"object"},"name":"remove_specific_memory"}]}}
    at crates/mcp-server/src/lib.rs:180
    in mcp_server::message_processing

  2025-02-06T00:49:24.554138Z  INFO mcp_server: incoming message, json: {"jsonrpc":"2.0","id":7,"method":"tools/call","params":{"arguments":{"category":"project_setup","data":"This is a Poetry-managed Python project for SpaceTraders game automation. Python version requirement: ^3.9","is_global":false,"tags":["poetry","python","dependencies"]},"name":"remember_memory"}}

    at crates/mcp-server/src/lib.rs:62

  2025-02-06T00:49:24.554166Z  INFO mcp_server: Received request, request_id: Some(7), method: "tools/call", json: {"jsonrpc":"2.0","id":7,"method":"tools/call","params":{"arguments":{"category":"project_setup","data":"This is a Poetry-managed Python project for SpaceTraders game automation. Python version requirement: ^3.9","is_global":false,"tags":["poetry","python","dependencies"]},"name":"remember_memory"}}
    at crates/mcp-server/src/lib.rs:150
    in mcp_server::message_processing

  2025-02-06T00:49:24.557588Z  INFO mcp_server: Sending response, response_id: Some(7), json: {"jsonrpc":"2.0","id":7,"result":{"content":[{"text":"Stored memory in category: project_setup","type":"text"}]}}
    at crates/mcp-server/src/lib.rs:180
    in mcp_server::message_processing

  2025-02-06T00:50:51.978632Z  INFO mcp_server: incoming message, json: {"jsonrpc":"2.0","id":8,"method":"tools/list","params":{}}

    at crates/mcp-server/src/lib.rs:62

  2025-02-06T00:50:51.978650Z  INFO mcp_server: Received request, request_id: Some(8), method: "tools/list", json: {"jsonrpc":"2.0","id":8,"method":"tools/list","params":{}}
    at crates/mcp-server/src/lib.rs:150
    in mcp_server::message_processing

  2025-02-06T00:50:51.978680Z  INFO mcp_server: Sending response, response_id: Some(8), json: {"jsonrpc":"2.0","id":8,"result":{"tools":[{"description":"Stores a memory with optional tags in a specified category","inputSchema":{"properties":{"category":{"type":"string"},"data":{"type":"string"},"is_global":{"type":"boolean"},"tags":{"items":{"type":"string"},"type":"array"}},"required":["category","data","is_global"],"type":"object"},"name":"remember_memory"},{"description":"Retrieves all memories from a specified category","inputSchema":{"properties":{"category":{"type":"string"},"is_global":{"type":"boolean"}},"required":["category","is_global"],"type":"object"},"name":"retrieve_memories"},{"description":"Removes all memories within a specified category","inputSchema":{"properties":{"category":{"type":"string"},"is_global":{"type":"boolean"}},"required":["category","is_global"],"type":"object"},"name":"remove_memory_category"},{"description":"Removes a specific memory within a specified category","inputSchema":{"properties":{"category":{"type":"string"},"is_global":{"type":"boolean"},"memory_content":{"type":"string"}},"required":["category","memory_content","is_global"],"type":"object"},"name":"remove_specific_memory"}]}}
    at crates/mcp-server/src/lib.rs:180
    in mcp_server::message_processing

### PR DESCRIPTION
**Pull request by yingjiehe-xyz**
fix #1108 

Sometimes the arguments can be empty and it will cause invalid json parsing error. We apply empty `{}` to avoid it.

Test:

Before:
```
( O)> list the window titles

I'll use the list_windows tool to show you all available window titles.
Invalid parameters: Could not interpret tool use parameters for id toolu_01CA9USw485HtvPTp53RXT68: EOF while parsing a value at line
 1 column 0


◓  Designing data dreams...            
2025-02-06T07:21:55.459232Z  WARN goose::providers::openrouter: Failed to get usage data: No usage data in response
    at crates/goose/src/providers/openrouter.rs:228


( O)> 

```

After
```
( O)> list the window titles
I'll help you list all available window titles using the `developer__list_windows` tool.

─── list_windows | developer ──────────────────────────



Here are all the available window titles that could be used with the screen capture tool. The list includes:
1. Several "Item-0" entries
2. System elements like Battery, WiFi, Clock, Menubar, and Dock
3. Application windows like:
   - "goose — goose session ▸ goose — 132×38"
   - "Threads - Block, Inc. - Slack"
   - "Downloads"
   - "BentoBox"

You can use any of these window titles with the screen_capture tool if you want to capture a specific window.

``

### CODE REVIEW

File: crates/goose/src/providers/formats/openai.rs [hunk 1]
```diff
@@ -183,10 +183,14 @@ pub fn response_to_message(response: Value) -> anyhow::Result<Message> {
                     .as_str()
                     .unwrap_or_default()
                     .to_string();
-                let arguments = tool_call["function"]["arguments"]
+                let mut arguments = tool_call["function"]["arguments"]
```
Comment (salman1993) [inline crates/goose/src/providers/formats/openai.rs:186]: would this work?
```
let arguments = tool_call["function"]["arguments"]
    .as_str()
    .unwrap_or_else(|| "{}")
    .to_string();
```

Comment (salman1993) [reply crates/goose/src/providers/formats/openai.rs:186]: can we also add in a tool with no arguments in the tool test here: https://github.com/block/goose/blob/8a399c41aca05364a00caaa1ed115c7d2cb7bc08/crates/goose/tests/providers.rs#L116

Comment (yingjiehe-xyz) [reply crates/goose/src/providers/formats/openai.rs:186]: I think `unwrap_or_else(|| "{}")` works for no `arguments` field, actually in our case, `arguments` does have value, it just has empty string.

Comment (yingjiehe-xyz) [reply crates/goose/src/providers/formats/openai.rs:186]: Also a question for the test, have we enabled the tests for providers? It seems like they are skipped by default: https://github.com/block/goose/blob/8a399c41aca05364a00caaa1ed115c7d2cb7bc08/crates/goose/tests/providers.rs#L318

Comment (yingjiehe-xyz) [reply crates/goose/src/providers/formats/openai.rs:186]: Just add unit test here

Comment (baxen) [reply crates/goose/src/providers/formats/openai.rs:186]: you need to setup a .env with credentials to run the provider integration tests, but yes they are current skipped in CI

**Review by baxen — APPROVED** [review]
LGTM

**Review by salman1993 — APPROVED** [review]
