### PR TITLE
Fix OpenAI empty choices panic

### LINKED ISSUE #4276: Panicked with OpenAI-compatible mlx_lm.server
**Describe the bug**

Panicked with a working OpenAI-compatible mlx_lm.server on macOS 15.6.1.

**To Reproduce**
1. Run mlx_lm.server with `lmstudio-community/Qwen3-4B-MLX-4bit`
2. Ensure the server works
3. Configure goose to use the server
4. Make sure goose found all available models
5. Query

**Expected behavior**
I expected to get a response from goose cli.

**Screenshots**

Image

**Please provide following information:**
 - **OS & Arch:** macOS 15.6.1 on MacBook Pro M1 2021 13"
 - **Interface:** CLI
 - **Version:** v1.5.0
 - **Provider & Model:** OpenAI - lmstudio-community/Qwen3-4B-MLX-4bit

**Additional context**
RUST_BACKTRACE=full:
```sh
starting session | provider: openai model: lmstudio-community/Qwen3-4B-MLX-4bit
    logging to /Users/mkozjak/.local/share/goose/sessions/20250822_124435.jsonl
    working directory: /Users/mkozjak

Goose is running! Enter your instructions, or try asking what goose can do.

Context: ○○○○○○○○○○ 0% (0/128000 tokens)
( O)> hello
◓  Mapping context vectors...
thread 'main' panicked at crates/goose/src/providers/formats/openai.rs:478:84:
index out of bounds: the len is 0 but the index is 0
stack backtrace:
◒  Mapping context vectors...                                                                                                   0:        0x1076fa18c - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hca5ddac00d0fe81d
   1:        0x107715744 - core::fmt::write::h345c34c786f611a2
   2:        0x1076c8a1c - std::io::Write::write_fmt::hf3ba17a7aed57370
   3:        0x1076fa084 - std::sys::backtrace::BacktraceLock::print::h5f3c3a4eb4693f7a
   4:        0x1076e0528 - std::panicking::default_hook::{{closure}}::haaa8c3be8e963b10
   5:        0x1076e0424 - std::panicking::default_hook::hf46b416954f6334b
   6:        0x1076e0b04 - std::panicking::rust_panic_with_hook::hae736c323e602f79
   7:        0x1076fa698 - std::panicking::begin_panic_handler::{{closure}}::h0f4c8174a03fed47
   8:        0x1076fa3b0 - std::sys::backtrace::__rust_end_short_backtrace::hc96ad38e8f461380
   9:        0x1076e0628 - __rustc[75b86e412cc6dff0]::rust_begin_unwind
  10:        0x1077db68c - core::panicking::panic_fmt::h6f546b4a6f225fa9
  11:        0x1077db80c - core::panicking::panic_bounds_check::hd382327e3f27e417
  12:        0x1069e0fdc - <async_stream::async_stream::AsyncStream<T,U> as futures_core::stream::Stream>::poll_next::hfdbef9deedd00789
  13:        0x1069dd904 - <async_stream::async_stream::AsyncStream<T,U> as futures_core::stream::Stream>::poll_next::h5f992b557c4d9d6c
  14:        0x1051b93cc - <async_stream::async_stream::AsyncStream<T,U> as futures_core::stream::Stream>::poll_next::hd9f8b3b4fef7cac7
  15:        0x1051fad98 - goose::agents::agent::Agent::reply_internal::{{closure}}::{{closure}}::hc6aa0e48387db047
  16:        0x1051b64a8 - <async_stream::async_stream::AsyncStream<T,U> as futures_core::stream::Stream>::poll_next::h0584de3f3d89745c
  17:        0x104ffb108 - <core::future::poll_fn::PollFn<F> as core::future::future::Future>::poll::h79edfaa660883a4b
  18:        0x104f41208 - goose_cli::session::Session::process_agent_response::{{closure}}::h62f3e2efd1f5db36
  19:        0x104f383d8 - goose_cli::session::Session::interactive::{{closure}}::h9ed6dd2874531469
  20:        0x104f26e48 - goose_cli::cli::cli::{{closure}}::h5a957a9c79e6a21d
  21:        0x104f6ca0c - goose::main::{{closure}}::hf6ef7b5286b6dbd5
  22:        0x10501e5b8 - tokio::runtime::park::CachedParkThread::block_on::hbfb7e8eb15ce5b8d
  23:        0x10525e790 - goose::main::h25eb38abe2385176
  24:        0x10535aa1c - std::sys::backtrace::__rust_begin_short_backtrace::hf584e981f3000ed7
  25:        0x1052aa18c - std::rt::lang_start::{{closure}}::h60bce630afd490e8
  26:        0x1076deb84 - std::rt::lang_start_internal::h7aa982cc60ae55c0
  27:        0x10525ea4c - _main
```

A working sample using `mlx_lm.chat`:
```sh
[INFO] Starting chat session with lmstudio-community/Qwen3-4B-MLX-4bit.
The command list:
- 'q' to exit
- 'r' to reset the chat
- 'h' to display these commands
>> hello
<think>
Okay, the user said "hello". I need to respond appropriately. Since they're greeting me, I should respond with a friendly greeting. Maybe "Hi there! How can I assist you today?" That sounds good. It's welcoming and opens the door for them to ask questions. I should keep it simple and positive. Let me make sure there's no markdown and that the response is natural. Yep, that should work.
</think>

Hi there! How can I assist you today? 😊
```

### PR DESCRIPTION
**Pull request by ARYPROGRAMMER**
### Summary

Fixed a panic error ("index out of bounds") that occurred when Goose interacted with OpenAI-compatible servers (like `mlx_lm.server` or `LM Studio`). The error was triggered when these servers sent response chunks with an empty `choices` array, as the code accessed elements like `response["choices"][0]` and `chunk.choices[0]` without checking if the array was empty first. The issue occurs rarely and is now almost guranteed to not occur.

---
### Root Cause Analysis (RCA, perhaps)

The panic was caused by unsafe array access in the OpenAI response parsing logic:

* **Streaming responses**: The `response_to_streaming_message()` function directly accessed `chunk.choices[0]` without performing a bounds check.
* **Non-streaming responses**: The `response_to_message()` function directly accessed `response["choices"][0]["message"]` without validating the array's existence or length.

While an empty `choices` array is valid according to the OpenAI specification, the existing code did not handle this case, leading to a crash.

---
### Technical Solution

Defensive bounds checking was implemented in both response parsing pathways to prevent the crash:

* **Streaming Response Handler (`response_to_streaming_message`)**
    * Added `!chunk.choices.is_empty()` guards before all accesses to `choices[0]`.
    * Added `!tool_chunk.choices.is_empty()` checks within tool call processing loops.
    * Replaced direct access with safe pattern matching and bounds validation.

* **Non-Streaming Response Handler (`response_to_message`)**
    * Added explicit validation using `response.get("choices").and_then(|c| c.as_array())`.
    * Included checks for empty arrays with descriptive error messages.
    * Switched from direct indexing to safe array access methods.

---
### Type of Change

- [ ] Feature
- [x] **Bug fix**
- [ ] Refactor / Code quality
- [ ] Performance improvement
- [ ] Documentation
- [ ] Tests
- [ ] Security fix
- [ ] Build / Release
- [ ] Other

---
### Testing

The fix was verified through the following steps:

* The project was built successfully using `cargo build`.
* Tests were conducted with an LM Studio server using both streaming and non-streaming requests.
* Confirmed that responses with empty `choices` arrays no longer cause panics.
* Verified that standard OpenAI API responses continue to work correctly.

Manual testing confirmed that Goose now gracefully handles empty `choices` arrays, ensuring compatibility with a wider range of OpenAI-compatible servers.

I can't actually test mlx server based but reverified with everything else. (needs apple chip)

---
### Related Issues

Fixes #4276 

---

### CODE REVIEW

File: crates/goose/src/providers/formats/openai.rs [hunk 1]
```diff
@@ -281,7 +281,14 @@ pub fn format_tools(tools: &[Tool]) -> anyhow::Result<Vec<Value>> {
 
 /// Convert OpenAI's API response to internal Message format
 pub fn response_to_message(response: &Value) -> anyhow::Result<Message> {
-    let original = &response["choices"][0]["message"];
+    let choices = response.get("choices").and_then(|c| c.as_array());
+    let choices = choices.ok_or_else(|| anyhow!("Response missing choices array"))?;
+
+    if choices.is_empty() {
+        return Err(anyhow!("Response contains empty choices array"));
+    }
```
Comment (DOsinga) [inline crates/goose/src/providers/formats/openai.rs]: this is probably good enough, but it feels more in line with the existing code to do something like:

```
let Some(original) = response
    .get("choices")
    .and_then(|c| c.get(0))
    .and_then(|m| m.get("message"))
else {
    return Ok(Message::with_content(Vec::new()));
};
```
i.e. if there is no content, we just return an empty message, same as if it is empty for other reasons below

**Review by DOsinga — APPROVED** [review]
thanks for fixing this. if you want I saw that databricks has a similar way of doing things.

File: crates/goose/src/providers/formats/openai.rs (hunk 1 above)
Comment (ARYPROGRAMMER) [reply crates/goose/src/providers/formats/openai.rs]: Thanks for the review and the great suggestion, i've implemented your recommended change to use the more standard pattern that returns an empty message instead of an error when choices are missing or empty. This is indeed more consistent with how the rest of the codebase handles empty content cases.

lgtm now @DOsinga

**Comment by ARYPROGRAMMER** [comment]
this is completed i think

File: crates/goose/src/providers/formats/openai.rs [hunk 2]
```diff
@@ -465,17 +472,19 @@ where
 
             if chunk.choices.is_empty() {
                 yield (None, usage)
-            } else if let Some(tool_calls) = &chunk.choices[0].delta.tool_calls {
+            } else if !chunk.choices.is_empty() && chunk.choices[0].delta.tool_calls.as_ref().is_some_and(|tc| !tc.is_empty()) {
```
Comment (DOsinga) [inline crates/goose/src/providers/formats/openai.rs]: here we aleady guard for empty though, don't we? on line 473?

Comment (ARYPROGRAMMER) [reply crates/goose/src/providers/formats/openai.rs]: yeah just for safety, should not impact

Comment (DOsinga) [reply crates/goose/src/providers/formats/openai.rs]: but it is redundant and makes the code harder to read; it signals to the reader that you were thinking something, so can we delete it?

**Comment by ARYPROGRAMMER** [comment]
just checking the build failure

**Comment by ARYPROGRAMMER** [comment]
@DOsinga please rerun ci pipelines for this, it should works now mostly

edit: 
1. removed redundant null check
2. fixed message::new constructor

**Comment by DOsinga** [comment]
there is still some of that checking going on I think

**Comment by ARYPROGRAMMER** [comment]
> there is still some of that checking going on I think

I think all have completed successfully now. 

Thanks, glad I was able to fix this

**Comment by ARYPROGRAMMER** [comment]
@taniandjerry can you please add Hacktoberfest and Large label to this. 

Thanks, I'll see this week's issues in a while
