### PR TITLE
fix[desktop]: Improve UX for ExtensionItem component

### LINKED ISSUE #6311: Extension card should not be clickable: a11y issue and causes accidental toggles
**Describe the bug**

The `ExtensionItem` component in the UI has accessibility issues due to nested interactive elements. The `Card` component (a `div`) has an `onClick` handler that toggles the extension, while also containing a `Switch` and a settings button (`Gear` icon) that are independently clickable. This creates several problems:

This is an accessibility issue and creates a poor user experience because:

* The Card shouldn't be clickable - that's what the Switch toggle is for and divs shouldn't contain click events
* Users accidentally click the card area (I do this all the time 😅) when trying to read extension details, unintentionally toggling the extension
* Having both the card and the switch toggle is confusing and unnecessary

---

**To Reproduce**
1. Navigate to Settings → Extensions in the Goose Desktop app
2. Use keyboard navigation (Tab key) to move through extension cards
3. Observe that focus indicators and interaction expectations are unclear
4. Use a screen reader to navigate the extensions list
5. Notice the lack of clear semantic information about interactive elements

---

**Expected behavior**

The Card itself should not be clickable. Only the interactive controls within it (the Switch and optional Settings button) should respond to user interaction. Each interactive element should have:
- Proper ARIA labels describing its purpose
- Clear focus indicators for keyboard navigation
- Semantic HTML that communicates functionality to assistive technologies
- No nested click handlers requiring event propagation management

---

**Proposed Solution**

Remove the `onClick` handler from the `<Card />` component and remove the `onClick={(e) => e.stopPropagation()}` from the `<CardAction />` component. Add proper ARIA labels to the Switch and Settings button. Remove `hover:cursor-pointer` from the Card since it's no longer clickable.

---

**Please provide the following information**
- **OS & Arch:** [All platforms]
- **Interface:** UI
- **Version:** [Current version]
- **Component:** `ui/desktop/src/components/settings/extensions/ExtensionItem.tsx`

---

**Additional context**

It doesn't affect keyboard navigation as the div is not focusable by default.

Image

### PR DESCRIPTION
**Pull request by Yorisoft**
## Summary

Fixes accessibility issues in the ExtensionItem component where the entire card was clickable, causing accidental toggles and poor accessibility.

### Type of Change

- [ ] Feature
- [x] Bug fix
- [ ] Refactor / Code quality
- [ ] Performance improvement
- [ ] Documentation
- [ ] Tests
- [ ] Security fix
- [ ] Build / Release
- [ ] Other (specify below)

---
- Removed `onClick` handler from Card component
- Removed `hover:cursor-pointer` and `hover:shadow-default` from Card (no longer clickable)
- Removed `e.stopPropagation()` from CardAction (no longer needed)
- Added `aria-label` attributes to the Settings button and Switch for screen reader support
----
### AI Assistance

- [ ] This PR was created or reviewed with AI assistance

### Testing

Manual testing - observed expected changes. 
  
- [x] Verified clicking on card area no longer toggles extension
- [x] Verified Switch toggle still works correctly
- [x] Verified Settings button still works correctly
- [x] Verified keyboard navigation works (Tab to focus, Enter/Space to activate)
  

### Related Issues
Relates to: fixes #6311  

### Screenshots/Demos (for UX changes)
Before:  

531284767-575c1aad-1117-40c1-88b4-c11f192605b1

After:   

https://github.com/user-attachments/assets/d52322a4-2750-49ba-ba59-80582712c8ae

### CODE REVIEW

File: ui/desktop/src/components/settings/extensions/subcomponents/ExtensionItem.tsx [hunk 1]
```diff
@@ -75,32 +75,33 @@ export default function ExtensionItem({
...
         <CardTitle>{getFriendlyTitle(extension)}</CardTitle>
 
-        <CardAction onClick={(e) => e.stopPropagation()}>
+        <CardAction>
           <div className="flex items-center justify-end gap-2">
             {editable && (
               <button
                 className="text-textSubtle hover:text-textStandard"
-                onClick={() => (onConfigure ? onConfigure(extension) : () => {})}
+                aria-label={`Configure ${getFriendlyTitle} Extension`}
```
Comment (lifeizhou-ap) [inline ui/desktop/src/components/settings/extensions/subcomponents/ExtensionItem.tsx]:
```suggestion
                aria-label={`Configure ${getFriendlyTitle(extension)} Extension`}
```

**Review by lifeizhou-ap — CHANGES_REQUESTED** [review]
Thanks a lot for your contribution to fixing this bug! Looks good!  

There's a small change needed in the inline comment below before we can merge.

File: ui/desktop/src/components/settings/extensions/subcomponents/ExtensionItem.tsx (hunk 1 above)
Comment (Yorisoft) [reply ui/desktop/src/components/settings/extensions/subcomponents/ExtensionItem.tsx]: Np - Fixed.
