### PR TITLE
fix: respond to interrupted tool calls with a ToolResponseMessageContent

### LINKED ISSUE #1541: Goose session breaks after stopping an in progress tool call
**Describe the bug**

Goose session breaks after stopping an in progress tool call

**To Reproduce**
1. Do a long running tool call like ping google 10 times
2. Cancel the operation midway
3. Type hi
4. You will see the 400 error

**Expected behavior**
The session should have resumed normally

**Screenshots**

Image

**Please provide following information:**
 - **OS & Arch:** [e.g. Ubuntu 22.04 x86]
 - **Interface:** [UI/CLI]
 - **Version:** [e.g. v1.0.2]
 - **Extensions enabled:** [e.g. Computer Controller, Figma]
 - **Provider & Model:** [e.g. Google - gemini-1.5-pro]

**Additional context**

### PR DESCRIPTION
**Pull request by kalvinnchau**
this fixes a bug where we we see an error about matching tool results
fixes #1541 

looks like during the conversion to use matching rust types in #1393 we missed this `onStop` implementation

this implementation attempts to match the logic in the CLI https://github.com/block/goose/blob/main/crates/goose-cli/src/session/mod.rs#L498-L536

### CODE REVIEW

File: ui/desktop/src/components/ChatView.tsx [hunk 1]
```diff
@@ -189,9 +197,45 @@ export default function ChatView({
       } else {
         setMessages([]);
       }
+    } else if (lastMessage.role === 'assistant') {
```
Comment (yingjiehe-xyz) [inline ui/desktop/src/components/ChatView.tsx]: also there is a special case, if the lastMessage is toolConfirmationRequest, we still need to append these response

**Review by Kvadratni — APPROVED** [review]

File: ui/desktop/src/components/ChatView.tsx (hunk 1 above)
Comment (kalvinnchau) [reply ui/desktop/src/components/ChatView.tsx]: updated to handle that

**Review by lily-de — APPROVED** [review]

File: ui/desktop/src/components/ChatView.tsx [hunk 2]
```diff
@@ -182,16 +191,70 @@ export default function ChatView({
...
+        // generate a response saying it was interrupted for each tool request
+        for (const [reqId, _] of toolRequests) {
+          const toolResponse: ToolResponseMessageContent = {
+            type: 'toolResponse',
+            id: reqId,
+            toolResult: {
+              status: 'error',
+              error: notification,
+            },
+          };
```
Comment (yingjiehe-xyz) [inline ui/desktop/src/components/ChatView.tsx:249]: nit: can we use createToolErrorResponseMessage util?

**Review by yingjiehe-xyz — APPROVED** [review]
