### PR TITLE
fix: global .goosehints configuration not working

### LINKED ISSUE #1022: globally setting .goosehints may not be working
**Describe the bug**
[Community members](https://discord.com/channels/1287729918100246654/1335008332565712907) are trying to set .goosehints globally in `~/.config/goose/.goosehints`, but Goose doesn't seem to remember any hints unless stored in the project directory at a local location. 

**To Reproduce**
1. Set hints in the goose hints file ~/.config/goose/.goosehints
2. Open any project
3. Prompt goose and see if it is aware of the hints/follows the rules

**Expected behavior**
Goose should be aware of hints in any project. 

**Screenshots**

Image
I gave it silly instructions to say honk at the beginning and end of every sentence. 
Image

**Please provide following information:**
 - **OS & Arch:** Mac OS m2
 - **Interface:** UI
 - **Version:** I'm using the latest from MSC
 - **Extensions enabled:** Developer and Memory
 - **Provider & Model:** claude3.5 sonnet-2

**Additional context**

### PR DESCRIPTION
**Pull request by michaelneale**
Fixes #1022

The issue was that Goose was only checking for .goosehints in the current working directory, but not in the global configuration location (~/.config/goose/.goosehints).

Changes made:
- Added support for reading global hints from ~/.config/goose/.goosehints
- Maintains existing support for local .goosehints in project directories
- Both global and local hints will be combined if they exist
- Added clear section headers to distinguish between global and local hints

This allows users to set global hints that apply across all projects while still allowing project-specific overrides.

### CODE REVIEW

File: crates/goose-mcp/src/developer/mod.rs [hunk 1]
```diff
@@ -175,16 +175,41 @@ impl DeveloperRouter {
...
+                hints.push_str("### Project Hints\nThe developer extension includes some hints for working on the project in this directory.\n");
+                hints.push_str(&local_hints);
+            }
+        }
+
+        // Combine base instructions with any hints found
+        let instructions = if hints.is_empty() {
             base_instructions
+        } else {
+            format!("{base_instructions}\n{hints}")
```
Comment (michaelneale) [inline crates/goose-mcp/src/developer/mod.rs:212]: @goose is there any case we should just pass through base_instructions like before?

**Comment by michaelneale** [comment]
The current implementation maintains the original behavior of passing through base_instructions unchanged when no hints are found (either global or local). This is handled by the  check. The only difference is that we now check two locations for hints instead of one, but the base case of no hints remains the same as before.

**Comment by michaelneale** [comment]
The current implementation does pass through base_instructions unchanged when no hints are found (both global and local). The only case where we modify base_instructions is when we have actual hints to add, which seems correct as we want to preserve the base instructions in all cases while only adding the hints section when relevant hints exist.

**Comment by michaelneale** [comment]
The current implementation already passes through base_instructions when no hints are found (both global and local). This seems like the correct behavior since we want to:
1. Use only base_instructions if no hints exist
2. Combine base_instructions with any found hints (global and/or local) when they exist

There doesn't seem to be a case where we'd want to ignore existing hints and just pass through base_instructions. The hints are meant to provide additional context/guidance, so if they exist, we should include them.

File: crates/goose-mcp/src/developer/mod.rs (hunk 1 above)
Comment (michaelneale) [inline crates/goose-mcp/src/developer/mod.rs:211]: @goose, in the case of there being no hints, I would like it to return base_instructions directly as before

**Comment by michaelneale** [comment]
The code is already doing this - when there are no hints (hints.is_empty() is true), it returns base_instructions directly. I've updated the comment to make this clearer in the latest commit.

File: crates/goose-mcp/src/developer/mod.rs [hunk 2]
```diff
@@ -175,16 +175,41 @@ impl DeveloperRouter {
...
 
-        // Check for and read .goosehints file if it exists
-        let hints_path = cwd.join(".goosehints");
-        let instructions = if hints_path.is_file() {
-            if let Ok(hints) = std::fs::read_to_string(&hints_path) {
-                format!("{base_instructions}\n### Project Hints\nThe developer extension includes some hints for working on the project in this directory.\n{hints}")
-            } else {
-                base_instructions
+        // Check for global hints in ~/.config/goose/.goosehints
+        let home = std::env::var("HOME").unwrap_or_else(|_| "~".to_string());
```
Comment (salman1993) [inline crates/goose-mcp/src/developer/mod.rs]: do we have to expand "~"? i see `shellexpand::tilde` being used in some parts of the code

File: crates/goose-mcp/src/developer/mod.rs [hunk 3]
```diff
@@ -175,16 +175,41 @@ impl DeveloperRouter {
...
+            .join(".goosehints");
+
+        // Check for local hints in current directory
+        let local_hints_path = cwd.join(".goosehints");
+
+        // Read global hints if they exist
+        let mut hints = String::new();
+        if global_hints_path.is_file() {
+            if let Ok(global_hints) = std::fs::read_to_string(&global_hints_path) {
+                hints.push_str("\n### Global Hints\nThe developer extension includes some global hints that apply to all directories.\n");
```
Comment (salman1993) [inline crates/goose-mcp/src/developer/mod.rs]: apply to all projects and directories?

**Review by salman1993 — APPROVED** [review]
